# -*- coding: utf-8 -*-
from app.learning.question_helper import make_mc

def get_questions_cinematica_extra():
    # 20 preguntas ya definidas
    q = []
    # Ejercicios
    q.append(make_mc('Un ciclista en MRU viaja a 8 m/s durante 45 s. ¿Que distancia recorre?', '360 m', ['320 m', '400 m', '280 m'], 'd = v*t = 8*45 = 360 m.', 'd = 360 m.', 'basic', 1150, '¿Que relacion vincula velocidad, tiempo y distancia en MRU?'))
    q.append(make_mc('Un movil parte del reposo con a = 2.5 m/s2 constante. ¿Rapidez a los 6.0 s?', '15.0 m/s', ['12.5 m/s', '17.5 m/s', '10.0 m/s'], 'v = a*t = 15 m/s.', 'v = 15 m/s.', 'basic', 1180, '¿Que formula relaciona aceleracion, tiempo y velocidad inicial nula?'))
    q.append(make_mc('Un auto a 20 m/s frena hasta detenerse en 50 m. ¿Modulo de aceleracion?', '4.0 m/s²', ['2.0 m/s²', '5.0 m/s²', '8.0 m/s²'], 'vf^2 = v0^2 - 2ad -> a = 4 m/s2.', 'a = 4 m/s2.', 'intermediate', 1220, 'Aplica la ecuacion de Torricelli independiente del tiempo.'))
    q.append(make_mc('Se lanza hacia arriba un cuerpo a 30 m/s (g = 10 m/s2). ¿Altura maxima?', '45.0 m', ['30.0 m', '60.0 m', '90.0 m'], 'Hmax = v0^2 / (2g) = 45 m.', 'Hmax = 45 m.', 'intermediate', 1230, '¿Que valor tiene la velocidad vertical en el punto mas alto?'))
    q.append(make_mc('¿Tiempo de caida libre desde 80 m de altura? (g = 10 m/s2)', '4.0 s', ['2.0 s', '5.5 s', '8.0 s'], 'h = 0.5gt^2 -> t = 4 s.', 't = 4 s.', 'basic', 1170, 'Despeja el tiempo a partir de la ecuacion de caida libre.'))
    q.append(make_mc('Un tren pasa de 10 m/s a 30 m/s en 5.0 s uniformemente. ¿Distancia?', '100 m', ['120 m', '80 m', '150 m'], 'd = v_media * t = 20 * 5 = 100 m.', 'd = 100 m.', 'intermediate', 1210, 'Multiplica la velocidad media por el tiempo.'))
    q.append(make_mc('Vector desplazamiento con dx = 6.0 m y dy = 8.0 m. ¿Modulo total?', '10.0 m', ['14.0 m', '7.0 m', '12.0 m'], 'Modulo = sqrt(36 + 64) = 10 m.', 'd = 10 m.', 'basic', 1160, 'Aplica el teorema de Pitagoras a las componentes ortogonales.'))
    q.append(make_mc('Movil parte de x = 12 m con v = -3 m/s constante. ¿Cuando cruza x = 0?', '4.0 s', ['3.0 s', '6.0 s', '2.5 s'], '0 = 12 - 3t -> t = 4 s.', 't = 4 s.', 'basic', 1150, 'Iguala la ecuacion horaria de posicion a cero.'))
    q.append(make_mc('En grafico v-t, la recta marca 15 m/s constante entre t = 2 s y 8 s. ¿Area?', '90 m', ['120 m', '60 m', '75 m'], 'Area = 6 * 15 = 90 m.', 'Area = 90 m.', 'intermediate', 1200, 'Calcula el area del rectangulo bajo la curva de velocidad.'))
    q.append(make_mc('Dos autos parten opuestos desde el mismo punto a 15 m/s y 25 m/s. ¿Separacion a 10 s?', '400 m', ['250 m', '100 m', '300 m'], 'd = (15+25)*10 = 400 m.', 'd = 400 m.', 'intermediate', 1210, 'Suma las distancias recorridas en sentidos opuestos.'))
    # Teoricas
    q.append(make_mc('En un grafico x(t), la pendiente de la recta tangente representa:', 'La velocidad instantanea del movil', ['La aceleracion media del movil', 'El desplazamiento acumulado', 'La fuerza aplicada'], 'Pendiente dx/dt es velocidad.', 'v = dx/dt.', 'basic', 1150, '¿Que razon de cambio espacial respecto al tiempo define la velocidad?'))
    q.append(make_mc('Si la velocidad es cero en un instante, ¿la aceleracion es obligadamente nula?', 'No, puede tener aceleracion no nula', ['Si, la aceleracion debe ser cero', 'Si, porque el objeto esta inmóvil', 'No, la aceleracion es infinita'], 'En altura maxima v=0 pero a = -g.', 'a puede ser distinta de cero.', 'intermediate', 1230, 'Pensa en el punto mas alto de un tiro vertical.'))
    q.append(make_mc('¿Que condicion define formalmente al MRUV?', 'Aceleracion constante y no nula', ['Velocidad constante y uniforme', 'Trayectoria parabolica plana', 'Aceleracion variable'], 'MRUV <=> a = constante.', 'a = constante.', 'basic', 1140, '¿Que magnitud cinematica permanece invariable en el MRUV?'))
    q.append(make_mc('El area bajo una curva aceleracion-tiempo a(t) representa:', 'El cambio de velocidad del movil', ['La posicion alcanzada', 'La distancia total', 'La fuerza resultante'], 'Integral de a dt = Delta v.', 'Delta v = area a(t).', 'intermediate', 1220, '¿Que magnitud resulta de multiplicar aceleracion por tiempo?'))
    q.append(make_mc('Si velocidad y aceleracion tienen signos opuestos, la rapidez:', 'Disminuye de forma progresiva', ['Aumenta de forma progresiva', 'Permanece constante', 'Se vuelve nula instantaneamente'], 'Signos contrarios implican frenado.', 'Rapidez decrece.', 'basic', 1160, '¿Que efecto produce una aceleracion opuesta a la marcha?'))
    q.append(make_mc('En tiro vertical libre sin aire, el tiempo de subida respecto al de bajada:', 'Son exactamente iguales entre si', ['El de subida es el doble', 'El de bajada es el doble', 'Depende de la masa'], 'Por simetria gravitatoria son iguales.', 't_subida = t_bajada.', 'basic', 1170, '¿Como influye que el modulo de g sea igual al subir y bajar?'))
    q.append(make_mc('La diferencia entre trayectoria y desplazamiento es:', 'La trayectoria es el camino y el desplazamiento un vector', ['La trayectoria es recta y el desplazamiento curvo', 'Ambos conceptos son identicos', 'La trayectoria es vectorial'], 'Trayectoria: curva; Desplazamiento: vector.', 'Delta r = rf - r0.', 'intermediate', 1210, '¿Cual magnitud depende del camino y cual une inicio con fin?'))
    q.append(make_mc('Una grafica x(t) con curvatura concava hacia arriba indica:', 'Aceleracion positiva constante', ['Aceleracion negativa constante', 'Velocidad uniforme', 'Aceleracion nula'], 'Concavidad positiva <=> a > 0.', 'a > 0.', 'intermediate', 1240, '¿Que signo de aceleracion corresponde a una curva hacia arriba?'))
    q.append(make_mc('Una aceleracion perpendicular a la velocidad en todo instante:', 'Modifica la direccion sin cambiar la rapidez', ['Aumenta la rapidez lineal', 'Frena al movil hasta pararlo', 'Invierte el sentido'], 'Aceleracion centripeta varia direccion.', 'Cambia direccion de v.', 'advanced', 1270, 'Si no hay componente tangencial, ¿puede cambiar el modulo?'))
    q.append(make_mc('El velocimetro de un automovil mide formalmente:', 'La rapidez escalar instantanea', ['La velocidad media vectorial', 'La aceleracion instantanea', 'El desplazamiento total'], 'Mide |v| sin orientacion.', 'Rapidez instantanea.', 'basic', 1140, '¿Indica el velocimetro hacia que punto cardinal viajas?'))
    return q


def get_questions_dinamica_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Cuerpo de 5.0 kg sobre piso liso recibe fuerza horizontal de 20 N. ¿Aceleracion?', '4.0 m/s²', ['2.5 m/s²', '5.0 m/s²', '10.0 m/s²'], 'a = 20 / 5 = 4 m/s2.', 'a = F/m = 4 m/s2.', 'basic', 1150, 'Aplica la Segunda Ley de Newton F = m*a.'))
    q.append(make_mc('Objeto de 8.0 kg pesa 78.4 N. ¿Cual es la gravedad local?', '9.8 m/s²', ['8.0 m/s²', '10.0 m/s²', '9.6 m/s²'], 'g = 78.4 / 8 = 9.8 m/s2.', 'g = P/m = 9.8 m/s2.', 'basic', 1140, 'Divide el peso entre la masa del objeto.'))
    q.append(make_mc('Bloque de 10 kg sobre superficie con μc = 0.30 (g = 10 m/s2). ¿Fuerza de rozamiento?', '30 N', ['3.0 N', '25 N', '33 N'], 'f_rc = 0.30 * 10 * 10 = 30 N.', 'f_rc = μc*N = 30 N.', 'basic', 1170, 'Multiplica el coeficiente cinetico por la normal.'))
    q.append(make_mc('Fuerza neta de 50 N actua sobre 25 kg en reposo durante 4.0 s. ¿Rapidez final?', '8.0 m/s', ['6.0 m/s', '10.0 m/s', '12.5 m/s'], 'a = 2 m/s2; v = 2 * 4 = 8 m/s.', 'v = a*t = 8 m/s.', 'intermediate', 1210, 'Halla la aceleracion y multiplicala por el tiempo.'))
    q.append(make_mc('Resorte con k = 200 N/m se comprime 0.05 m. ¿Fuerza elastica?', '10 N', ['4.0 N', '20 N', '40 N'], 'Fe = 200 * 0.05 = 10 N.', 'Fe = k*x = 10 N.', 'basic', 1160, 'Aplica la ley de Hooke multiplicando k por x.'))
    q.append(make_mc('Bloque de 4.0 kg baja por plano a 30° sin rozamiento (g = 10 m/s2). ¿Componente Px?', '20 N', ['40 N', '34.6 N', '10 N'], 'Px = 4 * 10 * sen(30) = 20 N.', 'Px = mg sen(30) = 20 N.', 'intermediate', 1220, 'Usa el seno del angulo para proyectar el peso en el plano.'))
    q.append(make_mc('Dos fuerzas ortogonales de 6.0 N y 8.0 N sobre 2.0 kg. ¿Aceleracion?', '5.0 m/s²', ['7.0 m/s²', '3.5 m/s²', '10.0 m/s²'], 'F_net = 10 N; a = 10 / 2 = 5 m/s2.', 'a = 10 / 2 = 5 m/s2.', 'intermediate', 1230, 'Calcula la resultante con Pitagoras y dividela por la masa.'))
    q.append(make_mc('Ascensor de 500 kg frena al bajar con a = 2 m/s2 hacia arriba (g = 10 m/s2). ¿Tension?', '6000 N', ['4000 N', '5000 N', '1000 N'], 'T = 500 * (10 + 2) = 6000 N.', 'T = m(g+a) = 6000 N.', 'advanced', 1260, 'Aplica Newton vertical considerando a hacia arriba.'))
    q.append(make_mc('Mover 50 kg requiere fuerza minima de 150 N (g = 10 m/s2). ¿Coeficiente μe?', '0.30', ['0.15', '0.45', '0.60'], 'μe = 150 / 500 = 0.30.', 'μe = F/N = 0.30.', 'intermediate', 1210, 'Divide la fuerza estatica maxima entre la normal.'))
    q.append(make_mc('Proyectil de 0.20 kg frena con fuerza de 50 N al penetrar madera. ¿Desaceleracion?', '250 m/s²', ['100 m/s²', '500 m/s²', '125 m/s²'], 'a = 50 / 0.20 = 250 m/s2.', 'a = F/m = 250 m/s2.', 'intermediate', 1220, 'Divide la fuerza de frenado entre la masa del proyectil.'))
    # Teoricas
    q.append(make_mc('Segun la Primera Ley de Newton, sin fuerzas externas netas un cuerpo conserva:', 'Su estado de reposo o MRU uniforme', ['Una aceleracion constante no nula', 'Un movimiento circular sin frenado', 'Una trayectoria espiral descendente'], 'Inercia: F_net = 0 implica v = constante.', 'F_net = 0 <=> v = constante.', 'basic', 1140, '¿Que predice el principio de inercia si la fuerza neta es cero?'))
    q.append(make_mc('El par de accion y reaccion de la Tercera Ley de Newton actua:', 'Siempre sobre dos cuerpos distintos', ['Siempre sobre el mismo objeto', 'Anulandose en el mismo objeto', 'Solo si los cuerpos se mueven'], 'Actuan sobre objetos distintos, no se anulan.', 'Accion y reaccion en cuerpos distintos.', 'basic', 1160, 'Si empujas la pared, ¿sobre quien actua cada fuerza?'))
    q.append(make_mc('La masa inercial de un objeto representa formalmente:', 'La medida cuantitativa de su inercia', ['La atraccion gravitatoria terrestre', 'El volumen espacial que ocupa', 'La lectura en dinamometro calibrado'], 'Mide la oposicion a cambiar de velocidad.', 'Masa inercial = resistencia a acelerar.', 'basic', 1150, '¿Que propiedad mide la oposicion al cambio de velocidad?'))
    q.append(make_mc('¿Por que el coeficiente estatico μe es mayor que el cinetico μc?', 'Porque las rugosidades encajan mas en reposo', ['Porque la normal disminuye al deslizarse', 'Porque la gravedad actua menos en reposo', 'Porque el area de contacto se anula'], 'En reposo las asperezas se traban con mas firmeza.', 'μe > μc por trabado estatico superficial.', 'intermediate', 1220, '¿Que requiere mas fuerza: iniciar el movimiento o mantenerlo?'))
    q.append(make_mc('Un vaso descansa en una mesa. ¿Reaccion a la fuerza peso del vaso?', 'La atraccion gravitatoria del vaso sobre la Tierra', ['La fuerza normal ejercida por la mesa', 'El rozamiento entre vaso y superficie', 'La fuerza de soporte de las patas'], 'Par del peso: atraccion gravitatoria hacia la Tierra.', 'Fuerza gravitatoria que el vaso hace a la Tierra.', 'advanced', 1260, 'El par debe ser de la misma naturaleza gravitatoria entre ambos cuerpos.'))
    q.append(make_mc('Una particula gira en curva a rapidez constante. ¿Actua una fuerza neta?', 'Si, una fuerza centripeta hacia el centro', ['No, porque la rapidez no esta cambiando', 'No, porque se encuentra en equilibrio', 'Solo si hay contacto con un fluido'], 'Variar la direccion implica aceleracion centripeta.', 'Giro curvo => fuerza centripeta no nula.', 'intermediate', 1220, '¿La velocidad cambia de orientacion al describir una curva?'))
    q.append(make_mc('Para que un bloque baje por un plano inclinado a rapidez constante:', 'El peso paralelo debe igualar al rozamiento', ['La normal debe anularse totalmente', 'No debe actuar gravedad sobre el bloque', 'El angulo debe ser de noventa grados'], 'Equilibrio dinamico: Px - f_rc = 0.', 'Px = f_rc para velocidad constante.', 'intermediate', 1210, '¿Que condicion de equilibrio exige la Primera Ley en el plano?'))
    q.append(make_mc('Si un astronauta en gravedad cero lanza una herramienta hacia adelante:', 'Retrocede hacia atras con menor aceleracion', ['Permanece inmovil en la misma posicion', 'Acelera hacia adelante junto a la pieza', 'Comienza a girar en su propio eje'], 'Tercera Ley: fuerza igual y opuesta hacia atras.', 'Accion y reaccion en sentido contrario.', 'basic', 1170, '¿Que predice la Tercera Ley sobre el emisor del empuje?'))
    q.append(make_mc('Al aumentar la inclinacion de un plano inclinado, la fuerza normal:', 'Disminuye conforme el coseno decrece', ['Aumenta conforme el seno se eleva', 'Permanece estrictamente constante', 'Se duplica al pasar los 45 grados'], 'N = mg*cos(θ). cos(θ) decrece con el angulo.', 'N disminuye al crecer la inclinacion.', 'intermediate', 1230, '¿Que ocurre con cos(θ) cuando el angulo sube hacia 90°?'))
    q.append(make_mc('La unidad del Sistema Internacional para la fuerza es el Newton (N), igual a:', 'kg·m/s²', ['kg·m²/s²', 'kg·m/s', 'Joule por segundo'], '1 N = 1 kg * 1 m/s2.', '1 N = 1 kg·m/s².', 'basic', 1140, 'Combina masa y aceleracion en la Segunda Ley de Newton.'))
    return q

def get_questions_trabajo_energia_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Fuerza de 40 N empuja una caja 5.0 m en su misma direccion. ¿Trabajo realizado?', '200 J', ['160 J', '240 J', '80 J'], 'W = 40 * 5 = 200 J.', 'W = 200 J.', 'basic', 1150, 'Multiplica fuerza por desplazamiento cuando son paralelos.'))
    q.append(make_mc('¿Cual es la energia cinetica de un automovil de 1200 kg a 20 m/s?', '240 kJ', ['120 kJ', '480 kJ', '24 kJ'], 'Ek = 0.5 * 1200 * 400 = 240 kJ.', 'Ek = 240000 J.', 'basic', 1170, 'Calcula un medio de la masa por el cuadrado de la rapidez.'))
    q.append(make_mc('Bloque de 3.0 kg se eleva 4.0 m con rapidez constante (g = 10 m/s2). ¿Energia potencial?', '120 J', ['60 J', '240 J', '30 J'], 'Epg = 3 * 10 * 4 = 120 J.', 'Epg = 120 J.', 'basic', 1160, 'Multiplica masa por gravedad y por la altura.'))
    q.append(make_mc('Resorte con k = 400 N/m se deforma 0.10 m. ¿Energia potencial elastica?', '2.0 J', ['4.0 J', '1.0 J', '8.0 J'], 'Epe = 0.5 * 400 * 0.01 = 2 J.', 'Epe = 2 J.', 'intermediate', 1200, 'Aplica la formula de energia elastica con la deformacion al cuadrado.'))
    q.append(make_mc('Se suelta una pelota desde 20 m sin rozamiento (g = 10 m/s2). ¿Rapidez al caer?', '20.0 m/s', ['14.1 m/s', '10.0 m/s', '25.0 m/s'], 'v = sqrt(2 * 10 * 20) = 20 m/s.', 'v = 20 m/s.', 'intermediate', 1220, 'Iguala la energia potencial gravitatoria inicial a la cinetica final.'))
    q.append(make_mc('Motor realiza trabajo util de 15000 J en 30 s. ¿Potencia mecanica media?', '500 W', ['450 W', '600 W', '300 W'], 'P = 15000 / 30 = 500 W.', 'P = 500 W.', 'basic', 1150, 'Divide el trabajo util entre el intervalo de tiempo transcurrido.'))
    q.append(make_mc('Trineo de 10 kg con v0 = 4 m/s recibe trabajo neto de 100 J. ¿Rapidez final?', '6.0 m/s', ['5.0 m/s', '7.2 m/s', '8.0 m/s'], 'Ek_f = 80 + 100 = 180 J -> vf = 6 m/s.', 'vf = 6 m/s.', 'intermediate', 1230, 'Suma el trabajo neto a la energia cinetica inicial.'))
    q.append(make_mc('Vagoneta pasa por A (h=15 m, v=10 m/s). ¿Rapidez en B a h=10 m? (g=10 m/s2)', '14.1 m/s', ['12.5 m/s', '16.0 m/s', '10.0 m/s'], 'vB = sqrt(100 + 2*10*5) = 14.1 m/s.', 'vB = 14.1 m/s.', 'advanced', 1260, 'Aplica conservacion de la energia mecanica total.'))
    q.append(make_mc('Fuerza de 50 N a 60° respecto al desplazamiento de 10 m. ¿Trabajo? (cos 60 = 0.50)', '250 J', ['500 J', '433 J', '125 J'], 'W = 50 * 10 * 0.5 = 250 J.', 'W = 250 J.', 'basic', 1160, 'Multiplica fuerza, distancia y el coseno del angulo formado.'))
    q.append(make_mc('Grua con P = 2000 W sube 400 kg a rapidez constante (g = 10 m/s2). ¿Rapidez?', '0.50 m/s', ['0.25 m/s', '1.0 m/s', '2.0 m/s'], 'v = 2000 / 4000 = 0.50 m/s.', 'v = 0.5 m/s.', 'intermediate', 1220, 'Divide la potencia entre el peso del cargamento.'))
    # Teoricas
    q.append(make_mc('Si una fuerza es perpendicular al desplazamiento en todo instante, su trabajo es:', 'Estrictamente nulo', ['Maximo y positivo', 'Maximo y negativo', 'Dependiente de la masa'], 'cos(90) = 0 implica trabajo nulo.', 'W = 0.', 'basic', 1140, '¿Que valor toma el coseno de 90 grados en el trabajo?'))
    q.append(make_mc('Segun el Teorema del Trabajo y la Energia Cinetica, el trabajo neto es igual a:', 'La variacion de energia cinetica', ['La perdida de energia potencial', 'La energia mecanica disipada', 'La potencia instantanea media'], 'W_neto = Delta Ek.', 'W_neto = Ek_f - Ek_i.', 'basic', 1160, '¿Que variacion energetica cuantifica el trabajo de todas las fuerzas?'))
    q.append(make_mc('¿Cual de las siguientes fuerzas es considerada no conservativa?', 'La fuerza de rozamiento cinetico', ['La atraccion gravitatoria', 'La fuerza elastica del muelle', 'La fuerza electrostatica'], 'La friccion disipa energia mecanica en calor.', 'Rozamiento = fuerza disipativa.', 'basic', 1150, '¿Que fuerza degrada energia en forma de calor irrecuperable?'))
    q.append(make_mc('En un sistema donde solo actuan fuerzas conservativas, se conserva:', 'La energia mecanica total', ['La velocidad de cada particula', 'La aceleracion instantanea', 'La energia potencial gravitatoria'], 'Sin disipacion, Em permanece constante.', 'Em = Ek + Ep = constante.', 'basic', 1150, '¿Que combinacion de energia cinetica y potencial permanece constante?'))
    q.append(make_mc('En un pendulo ideal sin rozamiento, la rapidez es maxima en:', 'El punto mas bajo de su trayectoria', ['Los extremos de maxima altura', 'Cualquier posicion intermedia', 'La rapidez es constante en el arco'], 'Ep minima en el fondo implica Ek maxima.', 'h minima => v maxima.', 'intermediate', 1210, '¿En que punto la altura y por tanto la energia potencial es minima?'))
    q.append(make_mc('Una persona sostiene una valija inmóvil a cierta altura durante 15 min. ¿Trabajo?', 'Cero, porque el desplazamiento es nulo', ['Un trabajo mecanico elevado', 'Un trabajo dependiente del tiempo', 'Un trabajo proporcional a la masa'], 'Sin desplazamiento (d=0) el trabajo es nulo.', 'W = F * 0 = 0.', 'basic', 1150, '¿Hubo algun cambio de posicion espacial de la valija?'))
    q.append(make_mc('La unidad del Sistema Internacional para energia y trabajo es el Joule, igual a:', 'Newton por metro (kg·m²/s²)', ['Watt por segundo al cuadrado', 'Newton sobre metro cuadrado', 'Kilogramo por metro sobre segundo'], '1 J = 1 N * 1 m = 1 kg*m2/s2.', '1 Joule = 1 N * m.', 'basic', 1140, 'Recuerda que trabajo es fuerza multiplicada por desplazamiento.'))
    q.append(make_mc('Si la rapidez de un vehiculo se triplica, su energia cinetica:', 'Se multiplica por nueve veces', ['Se multiplica por tres veces', 'Se multiplica por seis veces', 'Se reduce a la tercera parte'], 'Ek proporcional a v^2: (3v)^2 = 9v^2.', '3 al cuadrado es 9.', 'intermediate', 1200, 'Eleva el factor de aumento de velocidad al exponente dos.'))
    q.append(make_mc('El trabajo realizado por el rozamiento cinetico sobre un cuerpo que desliza es:', 'Siempre de signo negativo', ['Siempre de signo positivo', 'Nulo en cualquier tramo', 'Positivo si sube una rampa'], 'Friccion opuesta al desplazamiento: cos(180) = -1.', 'W < 0.', 'intermediate', 1210, '¿Que angulo forma la fuerza de rozamiento con el sentido de avance?'))
    q.append(make_mc('En un choque inelastico real, la energia mecanica total:', 'Disminuye al disiparse en calor y sonido', ['Se conserva perfectamente constante', 'Aumenta por liberacion elastica', 'Se transforma en potencial neta'], 'Parte de la energia se degrada en calor y deformacion.', 'Energia mecanica se degrada.', 'intermediate', 1220, '¿De donde proviene el sonido y la temperatura producida en el impacto?'))
    return q


def get_questions_cantidad_movimiento_extra():
    q = []
    # Ejercicios
    q.append(make_mc('¿Cual es el momento lineal de un proyectil de 0.05 kg que viaja a 400 m/s?', '20 kg·m/s', ['2.0 kg·m/s', '200 kg·m/s', '10 kg·m/s'], 'p = m*v = 0.05 * 400 = 20 kg*m/s.', 'p = 20 kg*m/s.', 'basic', 1150, 'Multiplica la masa por la velocidad vectorial.'))
    q.append(make_mc('Fuerza constante de 60 N actua durante 0.50 s sobre una pelota. ¿Impulso recibido?', '30 N·s', ['120 N·s', '15 N·s', '60 N·s'], 'I = F * Delta t = 60 * 0.50 = 30 N*s.', 'I = 30 N*s.', 'basic', 1150, 'Aplica el teorema del impulso multiplicando fuerza por tiempo.'))
    q.append(make_mc('Pelota de 0.40 kg lanzada a 15 m/s golpea una pared y rebota a 15 m/s en sentido opuesto. ¿Variacion de momento?', '12.0 kg·m/s', ['6.0 kg·m/s', '0.0 kg·m/s', '24.0 kg·m/s'], 'Delta p = m*(vf - vi) = 0.40*(15 - (-15)) = 0.40 * 30 = 12 kg*m/s.', 'Delta p = 12 kg*m/s.', 'intermediate', 1220, 'Recuerda que la velocidad es un vector: el rebote invierte su signo.'))
    q.append(make_mc('Un cuerpo de 2.0 kg a 6.0 m/s choca con otro de 4.0 kg en reposo y se unen (plastico). ¿Rapidez final?', '2.0 m/s', ['3.0 m/s', '1.5 m/s', '4.0 m/s'], 'Conservacion: 2*6 + 0 = (2+4)*vf -> 12 = 6*vf -> vf = 2 m/s.', 'vf = 12 / 6 = 2 m/s.', 'intermediate', 1210, 'Aplica la conservacion del momento lineal antes y despues del choque.'))
    q.append(make_mc('Un tirador de 70 kg dispara bala de 0.02 kg a 500 m/s. ¿Rapidez de retroceso del tirador?', '0.14 m/s', ['0.28 m/s', '1.40 m/s', '0.07 m/s'], '0 = 70*v_ret - 0.02*500 -> 70*v_ret = 10 -> v_ret = 0.14 m/s.', 'v_ret = 10 / 70 = 0.14 m/s.', 'intermediate', 1230, 'El momento lineal total inicial era cero: iguala los momentos opuestos.'))
    q.append(make_mc('Fuerza media frena un auto de 1000 kg desde 20 m/s hasta cero en 4.0 s. ¿Modulo de la fuerza media?', '5000 N', ['2500 N', '4000 N', '10000 N'], 'F_med = Delta p / Delta t = (1000*20) / 4 = 5000 N.', 'F = 20000 / 4 = 5000 N.', 'intermediate', 1210, 'Divide la variacion total del momento entre el tiempo de frenado.'))
    q.append(make_mc('Cuerpo de 3.0 kg con p = 18 kg·m/s. ¿Cual es su energia cinetica?', '54 J', ['27 J', '108 J', '36 J'], 'Ek = p^2 / (2m) = 324 / 6 = 54 J.', 'Ek = 18^2 / (2*3) = 54 J.', 'intermediate', 1240, 'Usa la formula que vincula energia cinetica con el momento al cuadrado.'))
    q.append(make_mc('Un vagon de 5000 kg a 2.0 m/s choca y engancha a otro identico en reposo. ¿Rapidez conjunta?', '1.0 m/s', ['0.5 m/s', '1.5 m/s', '2.0 m/s'], 'vf = (5000*2) / 10000 = 1.0 m/s.', 'vf = 1.0 m/s.', 'basic', 1160, 'La masa total se duplica, por lo que la velocidad resultante se reduce a la mitad.'))
    q.append(make_mc('Fuerza variable tiene grafico F(t) triangular de base 6.0 s y altura 100 N. ¿Impulso total?', '300 N·s', ['600 N·s', '150 N·s', '200 N·s'], 'Area de triangulo = base * altura / 2 = 6 * 100 / 2 = 300 N*s.', 'I = 6 * 100 / 2 = 300 N*s.', 'intermediate', 1220, 'El impulso corresponde al area bajo la curva en el grafico fuerza-tiempo.'))
    q.append(make_mc('Dos patinadores en reposo se empujan mutuamente. El de 40 kg sale a 3.0 m/s. ¿Rapidez del de 60 kg?', '2.0 m/s', ['3.0 m/s', '1.5 m/s', '4.5 m/s'], '40 * 3.0 = 60 * v2 -> 120 = 60*v2 -> v2 = 2.0 m/s.', 'v2 = 120 / 60 = 2 m/s.', 'intermediate', 1200, 'Iguala las magnitudes de los momentos de ambos patinadores.'))
    # Teoricas
    q.append(make_mc('En cualquier sistema aislado sin fuerzas externas netas, se conserva:', 'La cantidad de movimiento lineal total', ['La energia cinetica exclusivamente', 'La aceleracion de cada particula', 'La energia potencial gravitatoria'], 'F_ext = 0 implica dp/dt = 0 => p_total constante.', 'p_total se conserva.', 'basic', 1140, '¿Que principio fundamental rige a los sistemas mecanicos aislados?'))
    q.append(make_mc('El Teorema del Impulso establece que el impulso de la fuerza neta es igual a:', 'La variacion de cantidad de movimiento', ['La energia mecanica transferida', 'El trabajo realizado por la fuerza', 'La aceleracion media del proceso'], 'I = F*Delta t = Delta p.', 'I = Delta p.', 'basic', 1150, '¿Que cambio en el estado de movimiento genera la accion de una fuerza en un tiempo?'))
    q.append(make_mc('En una colision perfectamente inelastica (plastica):', 'Los cuerpos quedan unidos tras el impacto', ['Se conserva la energia cinetica total', 'Los cuerpos rebotan sin deformacion', 'El momento lineal total no se conserva'], 'En choque plastico los objetos continúan con una velocidad comun.', 'Cuerpos unidos tras el choque.', 'basic', 1160, '¿Que rasgo distintivo presentan los objetos al finalizar un choque plastico?'))
    q.append(make_mc('En un choque perfectamente elastico se conservan simultaneamente:', 'El momento lineal y la energia cinetica', ['Solo la cantidad de movimiento lineal', 'Solo la energia potencial gravitatoria', 'La rapidez individual de cada cuerpo'], 'Choque elastico: Delta p = 0 y Delta Ek = 0.', 'Se conservan p y Ek.', 'intermediate', 1210, '¿Que tipo de colision no presenta perdida alguna de energia cinetica?'))
    q.append(make_mc('¿Por que los autos modernos tienen zonas deformables en el chasis?', 'Para aumentar el tiempo de choque y bajar la fuerza', ['Para evitar que el auto rebote hacia atras', 'Para conservar mayor cantidad de movimiento', 'Para reducir la masa del vehiculo en el choque'], 'Mayor Delta t implica menor F_media para el mismo Delta p.', 'Mayor tiempo reduce la fuerza de impacto.', 'intermediate', 1220, 'Fijate en la relacion F_media = Delta p / Delta t.'))
    q.append(make_mc('El airbag de un automovil protege al pasajero principalmente porque:', 'Prolonga el tiempo en que se detiene el pasajero', ['Disminuye el cambio de momento lineal total', 'Elimina completamente la inercia del cuerpo', 'Aumenta la fuerza sobre el torax del ocupante'], 'Al extender Delta t, disminuye la fuerza de impacto recibida.', 'Mayor Delta t disminuye la fuerza sobre el cuerpo.', 'intermediate', 1220, 'Relaciona la fuerza media con el tiempo que tarda en frenar la cabeza.'))
    q.append(make_mc('La cantidad de movimiento lineal es una magnitud de naturaleza:', 'Vectorial con misma direccion que la velocidad', ['Escalar definida positiva en todo caso', 'Vectorial perpendicular a la velocidad', 'Adimensional en el Sistema Internacional'], 'p = m*v comparte direccion y sentido con v.', 'p es un vector paralelo a v.', 'basic', 1140, 'Dado que la masa es escalar positiva, ¿que direccion adopta el producto m*v?'))
    q.append(make_mc('En una explosion interna de un objeto inicialmente en reposo:', 'El centro de masa permanece inmóvil', ['Todos los fragmentos van en igual direccion', 'Se pierde la conservacion del momento lineal', 'La energia cinetica inicial era maxima'], 'Fuerzas internas conservan el momento total nulo.', 'Momento total sigue siendo cero.', 'advanced', 1250, 'Si no intervinieron fuerzas externas, ¿cambia el momento del sistema?'))
    q.append(make_mc('La unidad del Sistema Internacional para el impulso es N·s, equivalente a:', 'kg·m/s', ['kg·m²/s', 'kg·m/s²', 'Joule·segundo'], '1 N*s = (kg*m/s2)*s = 1 kg*m/s.', 'N*s = kg*m/s.', 'basic', 1140, 'Recuerda que el impulso equivale a la variacion del momento lineal.'))
    q.append(make_mc('Si una pelota de masa m rebota elasticamente contra el piso a rapidez v:', 'El cambio de momento tiene modulo 2mv', ['El cambio de momento es exactamente cero', 'El cambio de momento tiene modulo mv', 'El momento cinetico se anula al tocar'], 'Delta p = m*v - m*(-v) = 2mv.', 'Delta p = 2mv.', 'intermediate', 1230, 'Resta el vector velocidad final menos el vector inicial opuesto.'))
    return q

def get_questions_mov_circular_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Objeto describe circunferencia de radio 2.0 m con rapidez v = 6.0 m/s. ¿Aceleracion centripeta?', '18.0 m/s²', ['12.0 m/s²', '9.0 m/s²', '36.0 m/s²'], 'ac = v^2 / r = 36 / 2 = 18 m/s2.', 'ac = 36 / 2 = 18 m/s2.', 'basic', 1160, 'Aplica la formula ac = v^2 / r.'))
    q.append(make_mc('Piedra de 0.50 kg atada a cuerda de 1.0 m gira a 4.0 m/s en plano horizontal. ¿Fuerza centripeta?', '8.0 N', ['4.0 N', '16.0 N', '2.0 N'], 'Fc = m * v^2 / r = 0.5 * 16 / 1 = 8 N.', 'Fc = 8 N.', 'basic', 1160, 'Multiplica la masa por la aceleracion centripeta.'))
    q.append(make_mc('Rueda de 0.40 m de radio gira a velocidad angular constante de 10 rad/s. ¿Rapidez tangencial?', '4.0 m/s', ['2.5 m/s', '40 m/s', '0.04 m/s'], 'v = omega * r = 10 * 0.40 = 4.0 m/s.', 'v = 4 m/s.', 'basic', 1150, 'Multiplica la velocidad angular por el radio del circulo.'))
    q.append(make_mc('Un carrusel tarda 20 segundos en dar una vuelta completa. ¿Cual es su periodo T?', '20 s', ['0.05 s', '10 s', '40 s'], 'Periodo T es el tiempo de una vuelta: T = 20 s.', 'T = 20 s.', 'basic', 1130, '¿Que definicion tiene el periodo en un movimiento periodico?'))
    q.append(make_mc('Un ventilador gira con frecuencia de 30 Hz. ¿Cual es su velocidad angular omega?', '188.5 rad/s', ['94.2 rad/s', '60.0 rad/s', '30.0 rad/s'], 'omega = 2*pi*f = 2 * 3.1416 * 30 = 188.5 rad/s.', 'omega = 2*pi*30 = 188.5 rad/s.', 'intermediate', 1210, 'Aplica la relacion omega = 2*pi*f.'))
    q.append(make_mc('Auto de 1000 kg toma curva plana de 50 m de radio a 15 m/s. ¿Fuerza de rozamiento centripeta?', '4500 N', ['3000 N', '9000 N', '2250 N'], 'Fc = m*v^2 / r = 1000 * 225 / 50 = 4500 N.', 'Fc = 4500 N.', 'intermediate', 1220, 'Calcula la fuerza centripeta requerida para no derrapar en la curva.'))
    q.append(make_mc('Particula gira a 5.0 rad/s en radio de 0.80 m. ¿Aceleracion centripeta?', '20.0 m/s²', ['4.0 m/s²', '12.5 m/s²', '25.0 m/s²'], 'ac = omega^2 * r = 25 * 0.80 = 20 m/s2.', 'ac = 20 m/s2.', 'intermediate', 1210, 'Aplica ac = omega^2 * r.'))
    q.append(make_mc('Disco gira 120 vueltas en 60 segundos. ¿Cual es su frecuencia en Hertz?', '2.0 Hz', ['0.5 Hz', '120 Hz', '4.0 Hz'], 'f = vueltas / tiempo = 120 / 60 = 2.0 Hz.', 'f = 2 Hz.', 'basic', 1140, 'Divide el numero de vueltas entre los segundos transcurridos.'))
    q.append(make_mc('En curva de radio 80 m con μe = 0.50 (g = 10 m/s2), ¿rapidez maxima sin derrapar?', '20.0 m/s', ['15.0 m/s', '25.0 m/s', '10.0 m/s'], 'v_max = sqrt(μe * g * r) = sqrt(0.5 * 10 * 80) = sqrt(400) = 20 m/s.', 'v_max = 20 m/s.', 'advanced', 1250, 'Iguala la fuerza centripeta a la fuerza de rozamiento estatico maxima.'))
    q.append(make_mc('Cuerpo en MCU recorre arco de 15 m en 3.0 s en radio de 5.0 m. ¿Velocidad angular?', '1.0 rad/s', ['0.5 rad/s', '3.0 rad/s', '5.0 rad/s'], 'v = 15/3 = 5 m/s. omega = v / r = 5 / 5 = 1.0 rad/s.', 'omega = 1 rad/s.', 'intermediate', 1200, 'Calcula la rapidez tangencial y dividela por el radio.'))
    # Teoricas
    q.append(make_mc('En el Movimiento Circular Uniforme (MCU), la aceleracion centripeta apunta:', 'Hacia el centro de la circunferencia', ['Tangente a la trayectoria del giro', 'Opuesta al vector velocidad en la recta', 'Hacia afuera de la curvatura'], 'ac apunta radialmente hacia el centro de giro.', 'ac apunta hacia el centro.', 'basic', 1140, '¿Hacia donde indica la direccion radial de la fuerza centripeta?'))
    q.append(make_mc('En el MCU, ¿por que existe aceleracion si la rapidez escalar es constante?', 'Porque el vector velocidad cambia de orientacion', ['Porque el radio de giro se dilata continuamente', 'Porque actua la gravedad en cada punto del plano', 'Porque la masa del objeto varia al girar'], 'Velocidad varia en direccion, generando aceleracion centripeta.', 'Cambia la direccion de v.', 'basic', 1160, 'Recuerda que la velocidad es un vector: ¿basta variar la direccion para acelerar?'))
    q.append(make_mc('La relacion entre el periodo T y la frecuencia f en movimiento periodico es:', 'T = 1 / f', ['T = 2 * pi * f', 'T = f al cuadrado', 'T = omega / f'], 'Son magnitudes inversamente proporcionales: T * f = 1.', 'T = 1/f.', 'basic', 1130, '¿Que vinculo matematico relaciona el tiempo por vuelta con las vueltas por segundo?'))
    q.append(make_mc('La fuerza centripeta sobre un satelite en orbita circular terrestre es provista por:', 'La atraccion gravitatoria de la Tierra', ['El empuje de sus motores propulsores', 'La presion atmosferica del espacio', 'La fuerza magnetica del nucleo'], 'La gravedad provee la aceleracion centripeta orbital.', 'Gravedad actua como fuerza centripeta.', 'basic', 1150, '¿Que fuerza natural atrae continuamente al satelite hacia el centro de la Tierra?'))
    q.append(make_mc('Si una piedra atada a una cuerda se suelta mientras gira en MCU:', 'Sale disparada tangente a la circunferencia', ['Sale disparada radialmente hacia afuera', 'Cae directamente al centro del giro', 'Sigue girando en el aire unos instantes'], 'Por Primera Ley (inercia), continua por la recta tangente con v instantanea.', 'Sale tangente por inercia.', 'intermediate', 1210, '¿Hacia donde apuntaba su velocidad instantanea en el momento del corte?'))
    q.append(make_mc('La fuerza centrifuga que parece sentir un pasajero en una curva es:', 'Una fuerza ficticia debida al marco no inercial', ['Una fuerza real ejercida por el pavimento', 'El par de reaccion de la fuerza normal', 'La atraccion gravitatoria centrada'], 'Es un efecto inercial observado desde un sistema acelerado.', 'Fuerza inercial / ficticia en marco acelerado.', 'intermediate', 1230, '¿Es una interaccion real producida por algun cuerpo fisico tangible?'))
    q.append(make_mc('Al duplicar la rapidez en una curva conservando el radio, la aceleracion centripeta:', 'Se cuadruplica respecto a la inicial', ['Se duplica respecto a la inicial', 'Permanece estrictamente constante', 'Se reduce a la mitad del valor'], 'ac = v^2 / r. Duplicar v implica 2^2 = 4 veces mas ac.', 'ac crece con el cuadrado de v.', 'intermediate', 1210, 'Fijate en el exponente de la velocidad en la ecuacion de la aceleracion centripeta.'))
    q.append(make_mc('El peralte en una curva vial de ruta permite:', 'Que la normal aporte parte de la fuerza centripeta', ['Que la gravedad se anule completamente en el auto', 'Que el vehiculo pese menos durante la maniobra', 'Que no haya rozamiento en ninguna rueda'], 'La inclinacion descompone la normal, proveyendo fuerza hacia el centro.', 'La normal aporta componente centripeta.', 'intermediate', 1240, '¿Hacia donde apunta la componente horizontal de la fuerza normal en una curva inclinada?'))
    q.append(make_mc('La unidad en el Sistema Internacional para la velocidad angular es:', 'Radianes por segundo (rad/s)', ['Grados por segundo (°/s)', 'Revoluciones por minuto (rpm)', 'Metros por segundo (m/s)'], 'omega se mide en rad/s en el SI.', 'rad/s.', 'basic', 1140, '¿Cual es la unidad angular formal del SI combinada con el segundo?'))
    q.append(make_mc('En un disco solido que gira en torno a su centro, los puntos mas alejados del borde:', 'Tienen mayor rapidez tangencial que el centro', ['Tienen menor velocidad angular que el centro', 'Tienen menor aceleracion centripeta', 'Tienen el mismo periodo y menor rapidez'], 'Misma omega, pero v = omega*r aumenta con la distancia.', 'v = omega*r crece con el radio.', 'intermediate', 1220, 'Todos tardan el mismo tiempo por vuelta, pero ¿quien recorre un perimetro mas largo?'))
    return q


def get_questions_gravitacion_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Dos masas de 1000 kg estan separadas por 2.0 m. ¿Fuerza gravitatoria? (G = 6.67e-11)', '1.67e-5 N', ['3.34e-5 N', '6.67e-5 N', '8.34e-6 N'], 'F = 6.67e-11 * 1e6 / 4 = 1.667e-5 N.', 'F = G*m1*m2 / r^2 = 1.67e-5 N.', 'basic', 1160, 'Aplica la ley de gravitacion universal dividiendo entre la distancia al cuadrado.'))
    q.append(make_mc('Si la masa de la Tierra es 6.0e24 kg y el radio 6.4e6 m, ¿gravedad en superficie? (G = 6.67e-11)', '9.8 m/s²', ['10.5 m/s²', '8.9 m/s²', '11.2 m/s²'], 'g = G*M / R^2 = 6.67e-11 * 6e24 / (6.4e6)^2 = 9.77 m/s2.', 'g = 9.8 m/s2.', 'basic', 1160, 'Divide G*M entre el radio terrestre al cuadrado.'))
    q.append(make_mc('Un astronauta pesa 700 N en la Tierra. En la Luna (g_luna = 1.6 m/s2, g_tierra = 9.8 m/s2), ¿cuanto pesa?', '114 N', ['350 N', '700 N', '70 N'], 'm = 700 / 9.8 = 71.4 kg. P_luna = 71.4 * 1.6 = 114 N.', 'P = m * g_luna = 114 N.', 'basic', 1150, 'Halla la masa inalterable del astronauta y multiplicala por la gravedad lunar.'))
    q.append(make_mc('A una altura h igual al radio terrestre (r = 2R), ¿que valor tiene la gravedad?', '2.45 m/s²', ['4.90 m/s²', '9.80 m/s²', '1.22 m/s²'], 'g(2R) = g0 / 2^2 = 9.8 / 4 = 2.45 m/s2.', 'g = g0 / 4 = 2.45 m/s2.', 'intermediate', 1210, 'La gravedad cae con el cuadrado de la distancia al centro del planeta.'))
    q.append(make_mc('¿Cual es la velocidad orbital aproximada en orbita baja terrestre? (r = 6.4e6 m, g = 9.8 m/s2)', '7.9 km/s', ['11.2 km/s', '5.5 km/s', '9.8 km/s'], 'v_orb = sqrt(g * R) = sqrt(9.8 * 6.4e6) = 7919 m/s = 7.9 km/s.', 'v = sqrt(g*R) = 7.9 km/s.', 'intermediate', 1230, 'Iguala la fuerza gravitatoria a la centripeta y despeja la velocidad.'))
    q.append(make_mc('La velocidad de escape desde la superficie terrestre vale aproximadamente:', '11.2 km/s', ['7.9 km/s', '16.7 km/s', '22.4 km/s'], 'v_esc = sqrt(2 * g * R) = sqrt(2) * 7.9 = 11.2 km/s.', 'v_esc = sqrt(2)*v_orb = 11.2 km/s.', 'intermediate', 1220, 'Recuerda que la velocidad de escape es raiz de dos veces la orbital.'))
    q.append(make_mc('Dos satelites orbitan con radios r1 y r2 = 4*r1. Segun la 3ra Ley de Kepler, ¿relacion de periodos T2/T1?', '8', ['4', '2', '16'], 'T^2 proporcional a r^3 -> (T2/T1)^2 = 4^3 = 64 -> T2/T1 = 8.', 'T2/T1 = 4^(3/2) = 8.', 'advanced', 1260, 'Aplica la Tercera Ley de Kepler elevando la relacion de radios al cubo y sacando raiz.'))
    q.append(make_mc('Si la distancia entre dos planetas se reduce a la mitad, ¿por cuanto se multiplica su atraccion?', 'Cuatro veces', ['Dos veces', 'Ocho veces', 'Permanece igual'], 'F proporcional a 1/r^2: (1/0.5)^2 = 4.', 'F se multiplica por 4.', 'basic', 1150, 'Eleva el factor de reduccion de distancia al cuadrado inverso.'))
    q.append(make_mc('Un planeta tiene el doble de masa que la Tierra e igual radio. ¿Gravedad superficial?', '19.6 m/s²', ['9.8 m/s²', '4.9 m/s²', '39.2 m/s²'], 'g proporcional a M: g = 2 * 9.8 = 19.6 m/s2.', 'g = 2 * 9.8 = 19.6 m/s2.', 'basic', 1150, 'La gravedad es directamente proporcional a la masa del astro.'))
    q.append(make_mc('Periodo de un satelite geoestacionario alrededor de la Tierra:', '24 horas', ['12 horas', '48 horas', '1.5 horas'], 'Por definicion debe coincidir con la rotacion terrestre: 24 h.', 'T = 24 h = 1 dia.', 'basic', 1130, '¿Cuanto tarda la Tierra en dar una rotacion completa sobre su eje?'))
    # Teoricas
    q.append(make_mc('La Ley de Gravitacion Universal de Newton establece que la fuerza:', 'Decrece con el cuadrado de la distancia', ['Decrece linealmente con la distancia', 'Es independiente de la masa de los cuerpos', 'Es siempre repulsiva a distancias cortas'], 'F = G*m1*m2 / r^2: ley del inverso del cuadrado.', 'Ley del inverso del cuadrado.', 'basic', 1140, '¿Que potencia tiene la distancia en el denominador de la ley de Newton?'))
    q.append(make_mc('La constante de gravitacion universal G:', 'Es la misma en cualquier region del universo', ['Varia segun la altura sobre el mar', 'Depende de la temperatura del medio', 'Es valida unicamente en el Sistema Solar'], 'G es una constante universal fundamental de la fisica.', 'G es constante universal escalar.', 'basic', 1140, '¿Depende el valor de G del planeta o lugar donde se mida?'))
    q.append(make_mc('Segun la Primera Ley de Kepler, las orbitas planetarias son:', 'Elipses con el Sol en uno de los focos', ['Circulos perfectos centrados en el Sol', 'Parabolas abiertas hacia el espacio', 'Espirales convergentes al centro solar'], 'Primera Ley: orbitas elipticas con el Sol en un foco.', 'Elipses con el Sol en un foco.', 'basic', 1140, '¿Que figura conica descubrio Kepler en la orbita de Marte?'))
    q.append(make_mc('Segun la Segunda Ley de Kepler, el radio vector que une el planeta al Sol:', 'Barre areas iguales en tiempos iguales', ['Se mantiene constante en modulo y sentido', 'Tiene rapidez lineal uniforme en la orbita', 'Acelera unicamente en el afelio'], 'Ley de las areas: velocidad areolar constante.', 'Barre areas iguales en tiempos iguales.', 'intermediate', 1210, '¿Que magnitud geometrica se conserva proporcional al tiempo transcurrido?'))
    q.append(make_mc('El punto de la orbita planetaria mas cercano al Sol se denomina:', 'Perihelio', ['Afelio', 'Apogeo', 'Perigeo'], 'Perihelio: minima distancia al Sol; afelio: maxima.', 'Perihelio = punto mas cercano.', 'basic', 1130, 'El prefijo peri indica cercania y helios significa Sol.'))
    q.append(make_mc('Un planeta se desplaza con mayor rapidez orbital cuando pasa por:', 'El perihelio (mas cercano al Sol)', ['El afelio (mas lejano del Sol)', 'Los puntos medios de la elipse', 'La rapidez es estrictamente constante'], 'Por conservacion del momento angular, r menor implica v mayor.', 'Menor distancia => mayor rapidez orbital.', 'intermediate', 1210, 'Aplica la Segunda Ley de Kepler en la zona mas proxima al Sol.'))
    q.append(make_mc('La sensacion de ingravidez de los astronautas en la estacion espacial se debe a:', 'Que se encuentran en estado de caida libre continua', ['Que la gravedad es exactamente cero en el espacio', 'Que el campo magnetico compensa el peso', 'Que la atmosfera empuja el modulo hacia arriba'], 'Orbitar es caer libremente de forma continua alrededor del planeta.', 'Caida libre permanente en orbita.', 'intermediate', 1230, '¿Desaparece la fuerza gravitatoria a 400 km de altura o sigue actuando en caida libre?'))
    q.append(make_mc('La Tercera Ley de Kepler relaciona los periodos orbitales T y semiejes a como:', 'T² proporcional a a³', ['T proporcional a a', 'T³ proporcional a a²', 'T² proporcional a a'], 'T^2 / a^3 = constante para todos los planetas del Sol.', 'T² es proporcional a a³.', 'basic', 1150, '¿Que exponente lleva el periodo y cual el radio o semieje mayor?'))
    q.append(make_mc('El valor de la aceleracion de la gravedad g en la superficie depende de:', 'La masa y el radio del planeta considerado', ['La masa del objeto que esta cayendo', 'La velocidad inicial con que cae el cuerpo', 'La temperatura atmosferica reinante'], 'g = G*M / R^2 solo depende del planeta.', 'g = G*M / R^2.', 'basic', 1140, 'Recuerda que todos los cuerpos caen con la misma aceleracion independientemente de su masa.'))
    q.append(make_mc('Las mareas oceanicas en la Tierra se originan fundamentalmente por:', 'El gradiente de atraccion gravitatoria de la Luna y Sol', ['El calor emitido por la radiacion solar diurna', 'Las corrientes de vientos alisios marinos', 'El campo magnetico dipolar del nucleo'], 'La diferencia de fuerza gravitatoria entre el lado cercano y lejano genera la marea.', 'Fuerzas de marea por gradiente gravitatorio.', 'intermediate', 1220, '¿La atraccion de la Luna es mas fuerte en la cara de la Tierra mas proxima a ella?'))
    return q

def get_questions_estatica_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Fuerza de 25 N actua perpendicular a palanca con brazo de 0.80 m. ¿Torque?', '20 N·m', ['25 N·m', '16 N·m', '31 N·m'], 'tau = F * d = 25 * 0.80 = 20 N*m.', 'tau = 20 N*m.', 'basic', 1150, 'Multiplica fuerza por brazo de palanca cuando son perpendiculares.'))
    q.append(make_mc('Barra de 4.0 m apoyada en el centro tiene peso de 30 N a 1.0 m del apoyo. ¿Fuerza en el extremo (2 m) para equilibrar?', '15 N', ['30 N', '60 N', '7.5 N'], '30 * 1.0 = F * 2.0 -> F = 15 N.', 'F = 30 / 2 = 15 N.', 'basic', 1160, 'Iguala los torques en sentido horario y antihorario respecto al apoyo.'))
    q.append(make_mc('Lampara de 12 kg cuelga de dos cuerdas simetricas a 30° de la horizontal (g = 10 m/s2). ¿Tension en cada cuerda?', '120 N', ['60 N', '240 N', '208 N'], '2*T*sen(30) = mg -> 2*T*0.5 = 120 -> T = 120 N.', 'T = 120 / (2*0.5) = 120 N.', 'intermediate', 1230, 'Plantea el equilibrio vertical sumando las componentes verticales de ambas tensiones.'))
    q.append(make_mc('Fuerza de 50 N a 30° respecto a una barra de 2.0 m. ¿Modulo del torque? (sen 30 = 0.50)', '50 N·m', ['100 N·m', '86.6 N·m', '25 N·m'], 'tau = F * r * sen(30) = 50 * 2 * 0.5 = 50 N*m.', 'tau = 50 N*m.', 'basic', 1160, 'Multiplica fuerza, longitud del brazo y el seno del angulo.'))
    q.append(make_mc('Regla uniforme de 1.0 m y 2.0 N de peso. ¿En que posicion se ubica su centro de gravedad?', 'En la marca de 0.50 m', ['En la marca de 0.25 m', 'En la marca de 0.75 m', 'En el extremo de 1.0 m'], 'En cuerpos homogeneos simetricos el centro de masa esta en el centro geometrico.', 'x_cm = L/2 = 0.50 m.', 'basic', 1130, '¿Donde se ubica el punto medio de un objeto alargado y homogeneo?'))
    q.append(make_mc('Para aflojar una tuerca se necesita un torque de 60 N·m con llave de 0.30 m. ¿Fuerza minima perpendicular?', '200 N', ['180 N', '150 N', '300 N'], 'F = tau / d = 60 / 0.30 = 200 N.', 'F = 60 / 0.3 = 200 N.', 'basic', 1150, 'Divide el torque requerido entre la longitud de la herramienta.'))
    q.append(make_mc('Sobre un punto actuan F1 = 30 N hacia arriba y F2 = 40 N a la derecha. ¿Modulo de la fuerza equilibrante?', '50 N', ['70 N', '10 N', '35 N'], 'R = sqrt(30^2 + 40^2) = 50 N. La equilibrante tiene igual modulo.', 'Modulo de equilibrante = 50 N.', 'intermediate', 1210, 'La fuerza equilibrante tiene el mismo modulo que la resultante de las fuerzas dadas.'))
    q.append(make_mc('Viga horizontal uniforme de 6.0 m y 100 N de peso apoyada en ambos extremos A y B. ¿Fuerza de soporte en A?', '50 N', ['100 N', '25 N', '75 N'], 'Por simetria el peso se divide en partes iguales: 100 / 2 = 50 N.', 'R_A = 50 N.', 'basic', 1140, 'Al estar apoyada simetricamente, ¿como se reparte la carga entre los apoyos?'))
    q.append(make_mc('Palanca de primer genero tiene brazo de fuerza de 1.5 m y brazo de resistencia de 0.5 m. ¿Ventaja mecanica?', '3.0', ['0.33', '2.0', '1.0'], 'VM = brazo_fuerza / brazo_resistencia = 1.5 / 0.5 = 3.0.', 'VM = 3.', 'basic', 1150, 'Divide la longitud del brazo de fuerza entre el de resistencia.'))
    q.append(make_mc('Cuerpo en equilibrio sobre plano inclinado a 37° sin deslizar (g=10 m/s2). ¿Fuerza de rozamiento estatico de 10 kg? (sen 37 = 0.60)', '60 N', ['80 N', '100 N', '48 N'], 'f_re = Px = m*g*sen(37) = 10 * 10 * 0.60 = 60 N.', 'f_re = 60 N.', 'intermediate', 1210, 'La friccion estatica equilibra exactamente la componente del peso en el plano.'))
    # Teoricas
    q.append(make_mc('Para que un cuerpo rigido este en equilibrio estatico completo se deben cumplir:', 'Suma de fuerzas nula y suma de torques nula', ['Solo suma de fuerzas igual a cero', 'Solo suma de torques igual a cero', 'Que la velocidad sea distinta de cero'], 'Primera condicion: suma F = 0; Segunda condicion: suma tau = 0.', 'Equilibrio traslacional y rotacional simultaneos.', 'basic', 1140, '¿Que dos condiciones garantizan que un objeto no se traslade ni empiece a girar?'))
    q.append(make_mc('El momento de una fuerza (torque) respecto a un punto mide:', 'La capacidad de la fuerza de producir rotacion', ['La cantidad de movimiento lineal total', 'El trabajo desarrollado en una trayectoria', 'La deformacion permanente del material'], 'El torque cuantifica la tendencia al giro respecto a un eje.', 'Torque = efecto rotacional de una fuerza.', 'basic', 1140, '¿Que tipo de movimiento angular provoca la aplicacion de un torque?'))
    q.append(make_mc('El brazo de palanca de una fuerza se define formalmente como:', 'La distancia perpendicular de la linea de accion al eje', ['La longitud total de la barra que soporta la carga', 'La distancia entre el punto de apoyo y el piso', 'La distancia paralela a la fuerza aplicada'], 'Es la distancia minima (perpendicular) de la recta de accion al pivote.', 'Distancia perpendicular de la linea de fuerza al pivote.', 'intermediate', 1220, '¿Como debe medirse la distancia entre el eje de giro y la recta de la fuerza?'))
    q.append(make_mc('Si la linea de accion de una fuerza pasa exactamente por el eje de giro:', 'El torque producido es estrictamente nulo', ['El torque producido es maximo positivo', 'El torque producido es maximo negativo', 'El cuerpo acelera bruscamente en giro'], 'Brazo d = 0 implica tau = F * 0 = 0.', 'Brazo nulo => torque cero.', 'basic', 1150, '¿Existe alguna distancia perpendicular entre el punto de giro y la fuerza?'))
    q.append(make_mc('Un cuerpo apoyado se encuentra en equilibrio estable cuando:', 'Al inclinarlo levemente su centro de gravedad se eleva', ['Al inclinarlo levemente su centro de gravedad desciende', 'Cualquier inclinacion lo deja en nueva posicion neutra', 'Su base de sustentacion es un unico punto agudo'], 'El centro de gravedad sube y el peso genera un torque restaurador.', 'Equilibrio estable: centro de masa se eleva al perturbar.', 'intermediate', 1230, '¿Que le ocurre a la altura del centro de masa de una botella apoyada al ladearla un poco?'))
    q.append(make_mc('En una tijera de podar (palanca), la fuerza que se aplica en los mangos:', 'Se multiplica en las cuchillas por tener menor brazo', ['Se reduce a la mitad por conservacion de energia', 'Se anula en el punto de apoyo articulado', 'Es identica en valor a la que reciben las ramas'], 'VM = brazo_potencia / brazo_resistencia > 1 magnifica la fuerza.', 'Mayor brazo en mangos que en hojas amplifica la fuerza.', 'intermediate', 1210, '¿Como es la longitud de los mangos comparada con la de las cuchillas cortas?'))
    q.append(make_mc('La unidad del torque en el Sistema Internacional es:', 'Newton·metro (N·m)', ['Joule (J)', 'Watt (W)', 'Pascal (Pa)'], 'Aunque dimensionalmente sea N*m, no se usa Joule para evitar confusion con energia.', 'N·m.', 'basic', 1140, 'Multiplica la unidad de fuerza por la de distancia en el SI.'))
    q.append(make_mc('Un par de fuerzas (cupla) consiste en:', 'Dos fuerzas iguales, paralelas y de sentidos opuestos', ['Dos fuerzas perpendiculares del mismo modulo', 'Dos fuerzas concurrentes en el mismo punto', 'Dos fuerzas aplicadas sobre cuerpos separados'], 'Cupla: resultante nula pero torque neto no nulo.', 'Fuerzas de igual modulo, direccion paralela y sentido contrario.', 'intermediate', 1220, 'Pensa en el volante de un auto manejado con las dos manos.')),
    q.append(make_mc('El centro de gravedad de un cuerpo coincide con su centro de masa cuando:', 'El campo gravitatorio es uniforme en toda su extension', ['El cuerpo tiene forma perfectamente esferica', 'El cuerpo carece de masa inercial medible', 'El objeto se encuentra en el espacio exterior'], 'Si g es constante en todo el cuerpo, CG coincide con CM.', 'g uniforme => CG coincide con CM.', 'intermediate', 1230, '¿Que condicion debe cumplir la aceleracion gravitatoria a lo largo del cuerpo?'))
    q.append(make_mc('Si se empuja una puerta por su borde exterior en vez de cerca de la bisagra:', 'Se requiere menos fuerza para lograr el mismo torque', ['Se necesita mucha mas fuerza para hacerla girar', 'El torque resultante es exactamente igual a cero', 'La puerta no puede rotar por falta de friccion'], 'Mayor brazo d permite aplicar menor fuerza F para igual tau.', 'Mayor brazo requiere menor fuerza.', 'basic', 1140, '¿Por que el picaporte se ubica siempre en el extremo opuesto a las bisagras?'))
    return q


def get_questions_fluidos_extra():
    q = []
    # Ejercicios
    q.append(make_mc('¿Cual es la presion hidrostatica a 10 m de profundidad en agua dulce? (rho = 1000 kg/m3, g = 10 m/s2)', '100 kPa', ['10 kPa', '1000 kPa', '50 kPa'], 'P = rho*g*h = 1000 * 10 * 10 = 100000 Pa = 100 kPa.', 'P = 100000 Pa.', 'basic', 1150, 'Aplica la formula fundamental de la hidrostatica multiplicando densidad, gravedad y profundidad.'))
    q.append(make_mc('Bloque de volumen 0.02 m3 esta totalmente sumergido en agua (rho = 1000 kg/m3, g = 10 m/s2). ¿Empuje?', '200 N', ['100 N', '400 N', '20 N'], 'E = rho*V*g = 1000 * 0.02 * 10 = 200 N.', 'E = 200 N.', 'basic', 1150, 'Aplica el principio de Arquimedes multiplicando la densidad del liquido por el volumen sumergido y g.'))
    q.append(make_mc('Prensa hidraulica tiene pistones de areas A1 = 5 cm2 y A2 = 100 cm2. Con F1 = 50 N, ¿fuerza F2 lograda?', '1000 N', ['500 N', '2000 N', '250 N'], 'F2 = F1 * (A2/A1) = 50 * (100/5) = 50 * 20 = 1000 N.', 'F2 = 1000 N.', 'intermediate', 1210, 'Aplica el principio de Pascal: la presion se transmite igual a ambos pistones.'))
    q.append(make_mc('Un objeto pesa 80 N en el aire y 60 N sumergido en agua. ¿Cuanto vale el empuje que recibe?', '20 N', ['140 N', '80 N', '60 N'], 'E = Peso_real - Peso_aparente = 80 - 60 = 20 N.', 'E = 80 - 60 = 20 N.', 'basic', 1150, 'La diferencia entre el peso real y el peso aparente sumergido es el empuje.'))
    q.append(make_mc('Fuerza de 600 N se distribuye sobre una superficie plana de 0.03 m2. ¿Cual es la presion ejercida?', '20 kPa', ['18 kPa', '30 kPa', '6 kPa'], 'P = F / A = 600 / 0.03 = 20000 Pa = 20 kPa.', 'P = 20000 Pa.', 'basic', 1140, 'Divide la fuerza normal entre la superficie sobre la que apoya.'))
    q.append(make_mc('Un iceberg de densidad 900 kg/m3 flota en agua de mar (1000 kg/m3). ¿Que porcentaje de su volumen se sumerge?', '90%', ['80%', '95%', '10%'], 'V_sum / V_tot = rho_cuerpo / rho_liquido = 900 / 1000 = 0.90 = 90%.', 'V_sum / V_tot = 90%.', 'intermediate', 1220, 'Para un cuerpo flotante, la fraccion sumergida es la razon entre densidades.'))
    q.append(make_mc('En un manometro en U con mercurio (rho = 13600 kg/m3), el desnivel es 0.10 m (g = 9.8 m/s2). ¿Presion manometrica?', '13.3 kPa', ['9.8 kPa', '136 kPa', '6.8 kPa'], 'P = 13600 * 9.8 * 0.10 = 13328 Pa = 13.3 kPa.', 'P = 13.3 kPa.', 'intermediate', 1220, 'Multiplica la densidad del mercurio por la gravedad y el desnivel de columnas.'))
    q.append(make_mc('Un tanque tiene un orificio a 5.0 m bajo la superficie libre del agua (g = 10 m/s2). Segun Torricelli, ¿rapidez de salida?', '10.0 m/s', ['7.0 m/s', '14.1 m/s', '5.0 m/s'], 'v = sqrt(2 * g * h) = sqrt(2 * 10 * 5) = 10.0 m/s.', 'v = sqrt(2*g*h) = 10 m/s.', 'intermediate', 1230, 'Aplica el teorema de Torricelli para la velocidad de desagüe de un fluido ideal.'))
    q.append(make_mc('Barometro de Torricelli al nivel del mar sostiene una columna de mercurio de altura estandar de:', '760 mm', ['1000 mm', '500 mm', '76 mm'], '1 atmosfera equivale a 760 mmHg = 101325 Pa.', 'h = 760 mmHg.', 'basic', 1130, '¿Cual es el valor clasico de la presion atmosferica en milimetros de mercurio?'))
    q.append(make_mc('Cuerpo de 2.0 kg y volumen 0.003 m3 se suelta en agua (rho = 1000 kg/m3, g = 10 m/s2). ¿El cuerpo flota o se hunde?', 'Flota, porque su densidad es 667 kg/m3', ['Se hunde, porque su peso supera al empuje', 'Queda en equilibrio indiferente en el fondo', 'Flota con solo un 10% bajo el agua'], 'rho = m / V = 2 / 0.003 = 667 kg/m3 < 1000 kg/m3 => flota.', 'Flota (densidad menor a la del agua).', 'intermediate', 1210, 'Calcula la densidad del cuerpo y comparala con la densidad del agua.'))
    # Teoricas
    q.append(make_mc('El Principio de Pascal establece que la presion aplicada a un fluido incompresible encerrado:', 'Se transmite con igual valor en todas las direcciones', ['Se disipa proporcionalmente con la distancia', 'Solo se transmite hacia el fondo del recipiente', 'Aumenta con el cuadrado del volumen del liquido'], 'La presion se comunica integramente a todos los puntos del fluido.', 'Presion se transmite igual en todo el fluido.', 'basic', 1140, '¿Como se propaga la presion ejercida en un circuito hidraulico cerrado?'))
    q.append(make_mc('Segun el Principio de Arquimedes, el empuje hidrostatico sobre un cuerpo sumergido es igual a:', 'El peso del volumen de fluido desalojado', ['El peso propio del cuerpo en el vacio', 'La presion atmosferica sobre la superficie', 'La masa del liquido multiplicada por el volumen'], 'E = peso del fluido desplazado.', 'E = m_fluido_desalojado * g.', 'basic', 1150, '¿El empuje equivale al peso de que sustancia especifica?'))
    q.append(make_mc('La presion hidrostatica en el interior de un liquido en reposo depende de:', 'La densidad del liquido y la profundidad considerada', ['El area total del fondo del recipiente', 'La forma geometrica de las paredes del vaso', 'El volumen total de liquido acumulado'], 'P = rho*g*h: depende solo de densidad, gravedad y profundidad.', 'P = rho * g * h.', 'basic', 1140, 'Recuerda la paradoja hidrostatica: ¿influye la forma del recipiente en la presion a igual cota?'))
    q.append(make_mc('La paradoja hidrostatica demuestra que dos recipientes con distinta forma e igual liquido y nivel:', 'Tienen la misma presion en sus fondos', ['Tienen mayor presion en el recipiente mas ancho', 'Tienen menor presion en el recipiente mas alto', 'Generan fuerzas de igual modulo en cualquier base'], 'A igual altura h e igual liquido, la presion en el fondo es identica.', 'Misma altura => misma presion en el fondo.', 'intermediate', 1220, '¿Depende la presion hidrostatica de la cantidad total de agua o unicamente de la columna de liquido?'))
    q.append(make_mc('Un submarino se sumerge a mayor profundidad regulando su peso aparente mediante:', 'El llenado o vaciado de sus tanques de lastre con agua', ['El cambio de velocidad de giro de las helices', 'La modificacion de la forma exterior de su casco', 'El encendido de sistemas de calefaccion interna'], 'Inyectar agua aumenta el peso medio para que P > E y descienda.', 'Tanques de lastre modifican la densidad media.', 'basic', 1160, '¿Que entra o sale de los tanques del submarino para alterar su flotabilidad?'))
    q.append(make_mc('La presion atmosferica a nivel del mar disminuye a medida que se asciende a una montaña porque:', 'La columna de aire sobre el observador es menor', ['La aceleracion de la gravedad se vuelve nula', 'La temperatura del aire es mas elevada arriba', 'La densidad del aire se multiplica por diez'], 'Al subir hay menor masa de aire suprayacente ejerciendo peso.', 'Menor columna de atmosfera por encima.', 'basic', 1150, '¿Hay mas o menos capas de aire pesando sobre vos en la cima de un cerro?'))
    q.append(make_mc('La unidad del Sistema Internacional para la presion es el Pascal (Pa), que equivale a:', 'Newton sobre metro cuadrado (N/m²)', ['Newton por metro lineal (N·m)', 'Joule sobre metro cubico (J/m³)', 'Kilogramo por metro sobre segundo'], '1 Pa = 1 N / 1 m2.', 'Pascal = N/m².', 'basic', 1130, 'Recuerda que presion es la fuerza normal distribuida por unidad de superficie.'))
    q.append(make_mc('Cuando un cuerpo colocado en agua flota en equilibrio estatico:', 'El modulo del empuje iguala al modulo de su peso', ['El empuje es mucho mayor que el peso del cuerpo', 'La densidad del cuerpo supera a la del agua', 'El peso aparente es el doble de su peso real'], 'Equilibrio vertical: E - P = 0 => E = P.', 'E = P en flotacion estatica.', 'basic', 1150, 'Para que no ascienda ni se hunda, ¿como deben ser las fuerzas verticales?'))
    q.append(make_mc('La tension superficial en liquidos se origina por:', 'Fuerzas de atraccion no compensadas en la superficie libre', ['La presion atmosferica empujando las moleculas', 'El campo gravitatorio actuando solo en la frontera', 'El rozamiento entre el liquido y el recipiente'], 'Moleculas de la superficie sufren atraccion neta hacia el interior.', 'Fuerzas cohesivas intermoleculares en la superficie.', 'intermediate', 1230, '¿Que experimentan las moleculas del borde libre que no tienen mas liquido por encima?'))
    q.append(make_mc('El principio de los vasos comunicantes indica que en tubos conectados con un mismo liquido:', 'El nivel alcanzado es el mismo en todos los brazos', ['El tubo mas ancho tendra mayor nivel de agua', 'El tubo mas angosto tendra menor nivel de agua', 'El liquido fluye indefinidamente de un tubo a otro'], 'Para igualar presiones en la base, los niveles de superficie libre coinciden.', 'Mismo nivel libre en vasos comunicantes.', 'basic', 1140, '¿Como se comportan las alturas de agua en recipientes conectados entre si?'))
    return q

def get_questions_ondas_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Onda viaja a 340 m/s con frecuencia de 170 Hz. ¿Longitud de onda lambda?', '2.0 m', ['0.5 m', '4.0 m', '1.0 m'], 'lambda = v / f = 340 / 170 = 2.0 m.', 'lambda = 2 m.', 'basic', 1140, 'Divide la velocidad de propagacion entre la frecuencia.'))
    q.append(make_mc('Onda en cuerda tiene longitud de 0.50 m y periodo de 0.02 s. ¿Rapidez de propagacion?', '25.0 m/s', ['10.0 m/s', '50.0 m/s', '12.5 m/s'], 'v = lambda / T = 0.50 / 0.02 = 25 m/s.', 'v = 25 m/s.', 'basic', 1150, 'Divide la longitud de onda entre el periodo temporal.'))
    q.append(make_mc('Sonido viaja a 340 m/s y el eco de un acantilado se escucha a los 2.0 s. ¿Distancia al acantilado?', '340 m', ['680 m', '170 m', '510 m'], 'El sonido va y vuelve: d = v * t / 2 = 340 * 2 / 2 = 340 m.', 'd = 340 m.', 'intermediate', 1210, 'Recuerda que en el eco el sonido recorre dos veces la distancia (ida y vuelta).'))
    q.append(make_mc('Onda luminosa pasa de medio 1 (v1 = 3e8 m/s) a medio 2 (v2 = 2e8 m/s). Si f = 5e14 Hz, ¿lambda en medio 2?', '400 nm', ['600 nm', '500 nm', '300 nm'], 'lambda2 = v2 / f = 2e8 / 5e14 = 4e-7 m = 400 nm.', 'lambda2 = 400 nm.', 'intermediate', 1230, 'La frecuencia no cambia al refractarse; divide la nueva velocidad entre f.'))
    q.append(make_mc('Rayo incide a 30° en vidrio con n = 1.50 desde el aire (n1 = 1.00). ¿Seno del angulo refractado?', '0.33', ['0.50', '0.75', '0.25'], 'Snell: 1 * sen(30) = 1.5 * sen(r) -> sen(r) = 0.5 / 1.5 = 0.33.', 'sen(r) = 0.33.', 'intermediate', 1220, 'Aplica la Ley de Snell: n1 * sen(i) = n2 * sen(r).'))
    q.append(make_mc('Cuerda de 1.2 m fija en extremos vibra en su modo fundamental (1er armonico). ¿Longitud de onda?', '2.4 m', ['1.2 m', '0.6 m', '4.8 m'], 'En el fundamental L = lambda / 2 -> lambda = 2*L = 2.4 m.', 'lambda = 2.4 m.', 'intermediate', 1220, 'En el primer armonico la longitud de la cuerda equivale a media longitud de onda.'))
    q.append(make_mc('Una fuente emite 60 ondas completas cada 5.0 segundos. ¿Cual es su frecuencia en Hertz?', '12.0 Hz', ['6.0 Hz', '0.08 Hz', '24.0 Hz'], 'f = ciclos / tiempo = 60 / 5 = 12 Hz.', 'f = 12 Hz.', 'basic', 1140, 'Divide el numero de ciclos entre los segundos transcurridos.'))
    q.append(make_mc('Dos ondas coherentes en fase se superponen con amplitudes de 3.0 cm y 4.0 cm. ¿Amplitud resultante constructiva?', '7.0 cm', ['5.0 cm', '1.0 cm', '12.0 cm'], 'Interferencia constructiva: A_tot = A1 + A2 = 3 + 4 = 7 cm.', 'A = 7 cm.', 'basic', 1150, 'En interferencia constructiva pura las amplitudes individuales se suman directamente.'))
    q.append(make_mc('Ambulancia con sirena de 500 Hz se acerca a un observador en reposo. El tono percibido es:', 'Mas agudo (frecuencia mayor a 500 Hz)', ['Mas grave (frecuencia menor a 500 Hz)', 'Identico a 500 Hz en todo momento', 'Completamente inaudible por el movimiento'], 'Efecto Doppler: acercamiento comprime frentes de onda aumentando la frecuencia aparente.', 'f_aparente > 500 Hz.', 'basic', 1160, '¿Que le ocurre al tono sonoro de una fuente en movimiento cuando se aproxima hacia vos?'))
    q.append(make_mc('Rayo viaja de agua (n=1.33) a aire (n=1.00). ¿Seno del angulo critico limite para reflexion total?', '0.75', ['0.50', '0.67', '0.90'], 'sen(theta_c) = n2 / n1 = 1.00 / 1.33 = 0.75.', 'sen(theta_c) = 1 / 1.33 = 0.75.', 'advanced', 1260, 'Divide el indice de refraccion del medio exterior entre el del medio denso.'))
    # Teoricas
    q.append(make_mc('Una onda mecanica se caracteriza fundamentalmente porque:', 'Requiere un medio material elastico para propagarse', ['Se propaga unicamente en el vacio perfecto', 'Transporta materia a grandes distancias', 'Tiene siempre una rapidez igual a la de la luz'], 'Las ondas mecanicas necesitan soporte material (gas, liquido o solido).', 'Requiere medio material elastico.', 'basic', 1140, '¿Puede propagarse el sonido a traves del vacio del espacio exterior?'))
    q.append(make_mc('En una onda transversal, las particulas del medio oscilan:', 'Perpendicularmente a la direccion de propagacion', ['Paralelamente a la direccion de propagacion', 'En espirales abiertas hacia adelante', 'Permanecen completamente inmoviles'], 'Onda transversal: oscilacion perpendicular a la velocidad.', 'Oscilacion perpendicular a la propagacion.', 'basic', 1140, 'Pensa en las olas de una cuerda sacudida de arriba abajo.')),
    q.append(make_mc('En una onda sonora en el aire (onda longitudinal), las particulas oscilan:', 'Paralelamente a la direccion de propagacion', ['Perpendicularmente a la direccion de avance', 'En circulos transversales perfectos', 'Solo en el sentido del emisor inicial'], 'El sonido en fluidos es longitudinal: compresiones y rarefacciones paralelas.', 'Oscilacion paralela a la propagacion.', 'basic', 1150, '¿En que direccion se comprimen y descomprimen las capas de aire?'))
    q.append(make_mc('Cuando una onda pasa de un medio a otro con diferente rapidez (refraccion):', 'La frecuencia se mantiene estrictamente constante', ['La longitud de onda permanece constante', 'La velocidad de propagacion no varia', 'La amplitud se duplica en todo caso'], 'La frecuencia la determina el emisor y no cambia al refractar.', 'La frecuencia permanece constante.', 'intermediate', 1220, '¿Que propiedad de la oscilacion depende exclusivamente de la fuente original?'))
    q.append(make_mc('El fenomeno de difraccion consiste en:', 'La dispersion y curvado de la onda al sortear un obstaculo', ['El rebote de la onda al cambiar de medio denso', 'La disminucion de la frecuencia por absorcion', 'La separacion de la luz en colores componentes'], 'Difraccion: la onda rodea esquinas o pasa por rendijas angostas.', 'Onda rodea obstaculos o rendijas.', 'intermediate', 1210, '¿Como se llama la capacidad de una onda de rodear un borde y seguir avanzando?'))
    q.append(make_mc('Dos ondas generan interferencia totalmente destructiva en un punto cuando:', 'Llegan desfasadas en media longitud de onda (180°)', ['Llegan exactamente en fase simultaneamente', 'Tienen frecuencias completamente distintas', 'Sus rapideces de propagacion difieren en el medio'], 'Desfase de 180° (lambda/2) provoca cancelacion mutua de crestas y valles.', 'Desfase de 180° (lambda/2).', 'intermediate', 1220, '¿Que desfase hace coincidir la cresta de una onda con el valle de la otra?'))
    q.append(make_mc('El Efecto Doppler describe:', 'El cambio aparente de frecuencia por movimiento relativo', ['La perdida de energia acustica en el aire humedo', 'La polarizacion transversal de la luz visible', 'La reflexion total en limites de medios opticos'], 'Movimiento emisor-receptor altera la separacion de crestas percibidas.', 'Cambio de frecuencia percibida por movimiento.', 'basic', 1150, '¿Por que el sonido de una moto cambia de tono al acercarse y alejarse?'))
    q.append(make_mc('El tono o altura de un sonido esta determinado principalmente por:', 'La frecuencia de la vibracion de la onda sonora', ['La amplitud de presion de la onda sonora', 'La distancia entre el foco y el observador', 'La velocidad del viento en la atmosfera'], 'Mayor frecuencia = tono mas agudo; menor f = tono grave.', 'Tono depende de la frecuencia.', 'basic', 1140, '¿Que magnitud fisica distingue a una nota aguda de una nota grave?'))
    q.append(make_mc('El timbre de un instrumento musical nos permite:', 'Distinguir dos instrumentos que tocan la misma nota', ['Medir la velocidad a la que viaja el sonido', 'Calcular la distancia a la fuente acustica', 'Determinar el nivel sonoro en decibeles'], 'El timbre depende de la riqueza y proporcion de armonicos.', 'Timbre distingue fuentes por sus armonicos.', 'basic', 1150, '¿Por que una guitarra y un piano suenan diferente tocando la misma nota?'))
    q.append(make_mc('En una onda estacionaria, los puntos denominados nodos se caracterizan por:', 'Tener amplitud de oscilacion permanentemente nula', ['Oscilar con la maxima amplitud de la cuerda', 'Moverse con velocidad constante hacia adelante', 'Cambiar de posicion continuamente en el tiempo'], 'Nodos = interferencia destructiva continua (amplitud cero).', 'Nodos tienen amplitud cero.', 'basic', 1150, '¿Que amplitud de movimiento tienen los puntos fijos que no se mueven en la cuerda?'))
    return q

def get_questions_electricidad_5to_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Dos cargas puntuales de 2.0 microC estan a 0.30 m en el vacio (k = 9e9). ¿Fuerza de repulsion?', '0.40 N', ['0.12 N', '1.20 N', '0.04 N'], 'F = 9e9 * (2e-6)^2 / (0.3)^2 = 9e9 * 4e-12 / 0.09 = 0.40 N.', 'F = 0.40 N.', 'basic', 1160, 'Aplica la ley de Coulomb con las cargas en Coulombs y la distancia al cuadrado.'))
    q.append(make_mc('Carga de 4.0 microC experimenta fuerza de 0.02 N en un punto. ¿Intensidad del campo electrico?', '5000 N/C', ['2500 N/C', '10000 N/C', '500 N/C'], 'E = F / q = 0.02 / 4e-6 = 5000 N/C.', 'E = 5000 N/C.', 'basic', 1150, 'Divide la fuerza electrica entre el valor de la carga de prueba.'))
    q.append(make_mc('Resistencia de 20 ohms se conecta a una tension constante de 120 V. ¿Corriente que circula?', '6.0 A', ['4.0 A', '12.0 A', '2.4 A'], 'I = V / R = 120 / 20 = 6.0 A.', 'I = 6 A.', 'basic', 1140, 'Aplica la Ley de Ohm dividiendo el voltaje entre la resistencia.'))
    q.append(make_mc('¿Que potencia electrica disipa una bombilla conectada a 220 V que toma 0.50 A de corriente?', '110 W', ['220 W', '440 W', '55 W'], 'P = V * I = 220 * 0.50 = 110 W.', 'P = 110 W.', 'basic', 1140, 'Multiplica la diferencia de potencial por la intensidad de corriente.'))
    q.append(make_mc('Dos resistores de 30 ohms y 60 ohms se conectan en paralelo. ¿Resistencia equivalente?', '20 ohms', ['90 ohms', '45 ohms', '15 ohms'], 'Req = (30 * 60) / (30 + 60) = 1800 / 90 = 20 ohms.', 'Req = 20 ohms.', 'intermediate', 1210, 'Usa el producto sobre la suma para dos resistencias en paralelo.'))
    q.append(make_mc('Tres resistores de 10, 20 y 30 ohms se conectan en serie a 120 V. ¿Corriente total del circuito?', '2.0 A', ['1.0 A', '4.0 A', '6.0 A'], 'R_tot = 10 + 20 + 30 = 60 ohms. I = 120 / 60 = 2.0 A.', 'I = 2 A.', 'basic', 1150, 'Suma las resistencias en serie y aplica la Ley de Ohm general.'))
    q.append(make_mc('Al mover carga de 0.05 C entre dos puntos, el campo realiza trabajo de 1.5 J. ¿Diferencia de potencial?', '30 V', ['15 V', '60 V', '75 V'], 'Delta V = W / q = 1.5 / 0.05 = 30 V.', 'Delta V = 30 V.', 'intermediate', 1210, 'Divide el trabajo electrico entre la carga transportada.'))
    q.append(make_mc('Un calefactor de 1000 W funciona durante 2.0 horas. ¿Cuanta energia consume en kWh?', '2.0 kWh', ['1.0 kWh', '0.5 kWh', '4.0 kWh'], 'E = P * t = 1.0 kW * 2.0 h = 2.0 kWh.', 'E = 2 kWh.', 'basic', 1140, 'Multiplica los kilowatts de potencia por las horas de uso.'))
    q.append(make_mc('Si la distancia entre dos cargas se triplica, la fuerza electrica entre ellas:', 'Se reduce a la novena parte', ['Se reduce a la tercera parte', 'Se reduce a la sexta parte', 'Permanece inalterada'], 'F proporcional a 1/r^2: (1/3)^2 = 1/9.', 'F se divide entre 9.', 'basic', 1150, 'Eleva el factor de distancia al cuadrado en el denominador de Coulomb.'))
    q.append(make_mc('Conductor metalico transporta 24 C de carga en un intervalo de 8.0 s. ¿Corriente media?', '3.0 A', ['2.0 A', '4.0 A', '192 A'], 'I = Delta Q / Delta t = 24 / 8.0 = 3.0 A.', 'I = 3 A.', 'basic', 1140, 'Divide la cantidad total de carga entre el tiempo transcurrido.'))
    # Teoricas
    q.append(make_mc('La Ley de Coulomb establece que la fuerza entre dos cargas puntuales en reposo es:', 'Inversamente proporcional al cuadrado de la distancia', ['Directamente proporcional a la distancia que las separa', 'Independiente del medio dielectrico en que esten', 'Siempre atractiva independientemente del signo'], 'F = k*|q1*q2| / r^2: ley del inverso del cuadrado.', 'Ley del inverso del cuadrado de la distancia.', 'basic', 1140, '¿Que exponente tiene la distancia entre cargas en el divisor de Coulomb?'))
    q.append(make_mc('Las lineas de campo electrico creadas por una carga puntual positiva aislada:', 'Nacen en la carga y divergen hacia el infinito', ['Llegan desde el infinito y mueren en la carga', 'Forman bucles circulares cerrados continuos', 'Son paralelas entre si en todo el espacio'], 'Por convencion, las lineas salen de cargas positivas y entran a negativas.', 'Lineas nacen en cargas positivas y van al infinito.', 'basic', 1140, '¿Hacia donde apuntaria la fuerza sobre una carga de prueba positiva?'))
    q.append(make_mc('En un circuito electrico resistivo en serie, ¿que magnitud es comun a todos los elementos?', 'La intensidad de corriente electrica', ['La caida de potencial o voltaje', 'La potencia disipada individual', 'La energia consumida en un segundo'], 'En una sola rama serie la corriente no tiene bifurcaciones.', 'Misma corriente circula por todos los elementos en serie.', 'basic', 1150, 'Al no haber bifurcaciones o ramales, ¿puede variar el flujo de electrones?'))
    q.append(make_mc('En un circuito electrico con componentes en paralelo, todos los resistores comparten:', 'La misma diferencia de potencial (voltaje)', ['La misma intensidad de corriente', 'La misma resistencia equivalente neta', 'La misma direccion del campo magnetico'], 'Los extremos de cada rama estan conectados a los mismos dos nodos.', 'Mismo voltaje entre terminales paralelos.', 'basic', 1150, '¿A que bornes estan conectados los extremos de cada rama en paralelo?'))
    q.append(make_mc('Segun el efecto Joule, la energia electrica que se transforma en calor en un conductor es:', 'Proporcional al cuadrado de la intensidad de corriente', ['Inversamente proporcional a la resistencia del cable', 'Independiente del tiempo que circule corriente', 'Inversamente proporcional al voltaje aplicado'], 'E = I^2 * R * t: ley de Joule.', 'Proporcional a I al cuadrado.', 'intermediate', 1210, 'Fijate en el exponente que tiene la corriente en la formula P = I^2 * R.'))
    q.append(make_mc('La resistividad electrica rho de un material conductor metalico depende de:', 'La naturaleza del material y su temperatura', ['La longitud y el area transversal del cable', 'El voltaje de la bateria conectada al circuito', 'La corriente total que circula por la linea'], 'rho es propiedad intrinseca del material y temperatura.', 'Depende del material y la temperatura.', 'intermediate', 1220, 'Distingue entre resistencia geometrica R y resistividad intrinseca del material.'))
    q.append(make_mc('Un material se clasifica como aislante electrico porque:', 'Carece de electrones libres para transportar carga', ['Tiene demasiados protones libres en su corteza', 'Su resistencia electrica es cercana a cero ohms', 'Conduce corriente unicamente a bajas temperaturas'], 'Aislantes tienen bandas de valencia llenas y electrones fuertemente ligados.', 'Electrones fuertemente ligados sin movilidad.', 'basic', 1140, '¿Tienen los materiales plasticos o ceramicos electrones libres para desplazarse?'))
    q.append(make_mc('Al conectar un voltimetro para medir la tension en una resistencia, se debe conectar:', 'En paralelo con la resistencia', ['En serie intercalado en la rama', 'Directamente entre el neutro y tierra', 'Desconectando antes la fuente de tension'], 'El voltimetro mide diferencia de potencial entre dos puntos (en paralelo).', 'Conexion en paralelo.', 'basic', 1150, 'Para comparar el potencial antes y despues del elemento, ¿como se conectan las puntas?'))
    q.append(make_mc('El fusible de proteccion en una instalacion domiciliaria se conecta en:', 'Serie, para cortar la linea al exceder la corriente', ['Paralelo, para desviar la tension peligrosa', 'Tierra, para evitar descargas estaticas', 'Cualquier ramal sin importar la ubicacion'], 'El fusible debe interrumpir el paso de corriente abriendo el circuito.', 'Conexion en serie para interrumpir el paso.', 'basic', 1150, 'Si se derrite el hilo conductor, ¿como debe estar conectado para cortar la corriente?'))
    q.append(make_mc('La unidad de resistencia electrica en el Sistema Internacional es el Ohm (Omega), igual a:', 'Volt sobre Ampere (V/A)', ['Ampere sobre Volt (A/V)', 'Volt por Ampere (V·A)', 'Joule sobre Coulomb (J/C)'], 'R = V / I => 1 Ohm = 1 V / 1 A.', 'Ohm = Volt / Ampere.', 'basic', 1130, 'Despeja la resistencia a partir de la Ley de Ohm V = I * R.'))
    return q
