# -*- coding: utf-8 -*-
from app.learning.question_helper import make_mc

# ==============================================================================
# 6.º AÑO — 20 PREGUNTAS ADICIONALES POR TEMA (10 EJERCICIOS + 10 TEÓRICAS)
# Opciones de longitud balanceada, sin justificaciones delatadoras y con hints socráticos
# ==============================================================================

def get_questions_coulomb_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Cargas q1 = 3.0 microC y q2 = -5.0 microC a 0.20 m en vacio (k=9e9). ¿Modulo de la fuerza?', '3.38 N', ['1.69 N', '6.75 N', '0.68 N'], 'F = 9e9 * 3e-6 * 5e-6 / 0.04 = 3.375 N.', 'F = 3.38 N.', 'basic', 1200, 'Aplica la ley de Coulomb con los valores absolutos de las cargas.'))
    q.append(make_mc('Dos cargas identicas a 0.50 m se repelen con fuerza de 0.90 N en el vacio (k=9e9). ¿Valor de cada carga?', '5.0 microC', ['2.5 microC', '10.0 microC', '1.0 microC'], 'q^2 = F*r^2 / k = 0.90 * 0.25 / 9e9 = 2.5e-11 -> q = 5e-6 C = 5 microC.', 'q = 5.0 microC.', 'intermediate', 1240, 'Despeja la carga q igualando F a k*q^2 / r^2.'))
    q.append(make_mc('Si la distancia entre dos cargas puntuales se reduce a la tercera parte, la fuerza de Coulomb:', 'Se multiplica por 9', ['Se multiplica por 3', 'Se reduce a 1/9', 'Se triplica'], 'F proporcional a 1/r^2: (1 / (1/3))^2 = 9.', 'F aumenta 9 veces.', 'basic', 1180, 'Eleva el factor de reduccion de distancia al cuadrado inverso.'))
    q.append(make_mc('Cargas q1 = +2 microC y q2 = +8 microC separadas 1.0 m. ¿A que distancia de q1 la fuerza neta sobre una 3ra carga es cero?', '0.33 m', ['0.50 m', '0.25 m', '0.67 m'], 'k*2/x^2 = k*8/(1-x)^2 -> 1/x = 2/(1-x) -> 1-x = 2x -> 3x = 1 -> x = 0.33 m.', 'x = 0.33 m desde q1.', 'advanced', 1280, 'Iguala las fuerzas de Coulomb que ejercen ambas cargas sobre la carga de prueba.'))
    q.append(make_mc('Fuerza electrostatica entre dos esferas conductoras descargadas y frotadas que intercambian 1.0e13 electrones a 0.10 m (e=1.6e-19, k=9e9):', '2.3 N', ['1.2 N', '4.6 N', '0.58 N'], 'q = 1e13 * 1.6e-19 = 1.6e-6 C. F = 9e9 * (1.6e-6)^2 / 0.01 = 2.304 N.', 'F = 2.3 N.', 'intermediate', 1250, 'Calcula la carga neta multiplicando el numero de electrones por la carga elemental e.'))
    q.append(make_mc('Carga de +10 microC y otra de -10 microC estan en x = -0.10 m y x = +0.10 m. ¿Fuerza sobre q = +1 microC en el origen?', '18.0 N hacia la derecha', ['9.0 N hacia la derecha', '18.0 N hacia la izquierda', '0.0 N en el origen'], 'Ambas fuerzas empujan/atraen hacia +x: F_tot = 2 * (9e9 * 10e-6 * 1e-6 / 0.01) = 2 * 9 = 18 N.', 'F = 18 N hacia +x.', 'advanced', 1290, 'Suma vectorialmente la fuerza de repulsion de la positiva y de atraccion de la negativa.'))
    q.append(make_mc('Dos esferas identicas con cargas +6 microC y -2 microC se tocan y se vuelven a separar. ¿Carga final de cada una?', '+2.0 microC', ['+4.0 microC', '+1.0 microC', '0.0 microC'], 'q_promedio = (+6 - 2) / 2 = +4 / 2 = +2 microC.', 'q = +2 microC.', 'basic', 1190, 'Al tocarse esferas conductoras identicas, la carga neta se reparte equitativamente.'))
    q.append(make_mc('¿Que aceleracion experimenta un electron (m = 9.1e-31 kg, q = 1.6e-19 C) sometido a fuerza electrica de 3.64e-15 N?', '4.0e15 m/s²', ['2.0e15 m/s²', '8.0e15 m/s²', '1.0e15 m/s²'], 'a = F / m = 3.64e-15 / 9.1e-31 = 4.0e15 m/s2.', 'a = 4.0e15 m/s2.', 'intermediate', 1230, 'Aplica la Segunda Ley de Newton dividiendo la fuerza entre la masa del electron.'))
    q.append(make_mc('Fuerza entre dos cargas en el vacio es 100 N. Si se sumergen en un medio de constante dielectrica relativa epsilon_r = 5:', '20 N', ['500 N', '50 N', '10 N'], 'F_medio = F_vacio / epsilon_r = 100 / 5 = 20 N.', 'F = 20 N.', 'intermediate', 1220, 'La permitividad relativa de un dielectrico reduce la fuerza electrica en ese factor.'))
    q.append(make_mc('Carga de 1.0 C equivale a la carga combinada de aproximadamente:', '6.25e18 electrones', ['1.60e19 electrones', '3.12e18 electrones', '6.02e23 electrones'], 'N = 1.0 / 1.602e-19 = 6.24e18 electrones.', 'N = 6.25e18 electrones.', 'basic', 1180, 'Divide un Coulomb entre la magnitud de la carga fundamental del electron.'))
    # Teoricas
    q.append(make_mc('La Ley de Coulomb es valida estrictamente para:', 'Cargas puntuales en reposo relativo', ['Conductores de cualquier forma en movimiento', 'Cargas en movimiento con corrientes elevadas', 'Campos magneticos dipolares intensos'], 'Valida para electrostatica de cargas puntuales o esfericas estaticas.', 'Cargas puntuales estaticas.', 'basic', 1170, '¿Que condicion cinematica exige la electrostatica clasica de Coulomb?'))
    q.append(make_mc('El principio de conservacion de la carga electrica postula que:', 'La carga neta total de un sistema aislado es constante', ['Las cargas positivas pueden destruirse espontaneamente', 'La carga de cada cuerpo no puede variar jamas', 'No se pueden transferir electrones entre cuerpos'], 'La carga no se crea ni destruye, solo se redistribuye.', 'Carga neta se conserva en sistemas aislados.', 'basic', 1160, '¿Que ocurre con la suma algebraica de todas las cargas en un sistema cerrado?'))
    q.append(make_mc('La cuantizacion de la carga electrica significa que:', 'Cualquier carga es multiplo entero de la carga elemental e', ['La carga solo existe en magnitudes continuas infinitas', 'Todos los cuerpos tienen carga estrictamente nula', 'La carga depende linealmente de la velocidad del cuerpo'], 'q = n * e, con n entero.', 'Carga existe en paquetes discretos de e.', 'basic', 1170, '¿Puede un cuerpo aislado tener una fraccion decimal como 0.5 electrones?'))
    q.append(make_mc('El par de fuerzas electrostáticas entre dos cargas de signos contrarios es:', 'Atractivo y cumple la Tercera Ley de Newton', ['Repulsivo y no cumple la Tercera Ley de Newton', 'Atractivo y de diferente magnitud en cada una', 'Nulo debido a la cancelacion mutua de signos'], 'Signos opuestos se atraen con fuerzas iguales y opuestas.', 'Fuerzas atractivas de igual modulo y sentidos contrarios.', 'basic', 1160, 'Recuerda que la interaccion mutua siempre obedece accion y reaccion.'))
    q.append(make_mc('La constante k de Coulomb en el Sistema Internacional se expresa como:', '1 / (4 * pi * epsilon_0)', ['4 * pi * epsilon_0', 'epsilon_0 / (4 * pi)', 'mu_0 / (4 * pi)'], 'k = 1 / (4 * pi * epsilon_0) aprox 8.99e9 N*m2/C2.', 'k = 1 / (4*pi*epsilon_0).', 'basic', 1160, '¿Como se vincula la constante k con la permitividad del vacio epsilon_0?'))
    q.append(make_mc('Al frotar una varilla de vidrio con seda, la varilla adquiere carga positiva porque:', 'Cede electrones a la tela de seda', ['Absorbe protones del tejido de seda', 'Destruye electrones de su propia estructura', 'Crea protones por efecto de la friccion'], 'En solidos solo los electrones tienen movilidad para transferirse.', 'Los electrones pasan del vidrio a la seda.', 'basic', 1150, '¿Cuales particulas subatomicas tienen movilidad para pasar de un material a otro?'))
    q.append(make_mc('La constante dielectrica relativa de un medio material aislante es siempre:', 'Mayor o igual a uno (epsilon_r >= 1)', ['Menor que uno en todo aislante', 'Estrictamente negativa en liquidos', 'Igual a cero para conductores ideales'], 'En cualquier medio material la fuerza electrostatica disminuye respecto al vacio (epsilon_r >= 1).', 'epsilon_r >= 1.', 'intermediate', 1220, '¿Aumenta o debilita la polarizacion del medio dielectrico la fuerza entre cargas?'))
    q.append(make_mc('El principio de superposicion electrostatica establece que la fuerza sobre una carga:', 'Es la suma vectorial de las fuerzas individuales de las demas', ['Es el producto escalar de las fuerzas individuales', 'Es igual a la fuerza de la carga mas cercana unicamente', 'Es el promedio aritmetico de las fuerzas actuantes'], 'F_tot = suma de F_i vectoriales independientes.', 'Suma vectorial de fuerzas individuales.', 'basic', 1160, '¿Como se combinan las fuerzas de varias cargas sobre un punto?'))
    q.append(make_mc('Si una carga positiva Q se ubica en el centro de un cascaron esferico conductor descargado:', 'Se induce carga -Q en la cara interna y +Q en la externa', ['El cascaron queda uniformemente negativo en todo volumen', 'La carga interna Q es neutralizada y desaparece', 'No se induce carga alguna por estar descargado'], 'Induccion electrostatica: campo interno nulo exige -Q adentro y +Q afuera.', 'Induce -Q adentro y +Q afuera.', 'advanced', 1270, 'Aplica la condicion de campo nulo en el interior del metal conductor en equilibrio.'))
    q.append(make_mc('La unidad del Sistema Internacional para la carga electrica es el Coulomb (C), definido como:', 'Ampere por segundo (A·s)', ['Volt sobre Ohm (V/Omega)', 'Joule por segundo (J/s)', 'Newton sobre metro (N/m)'], 'I = q/t => 1 C = 1 A * 1 s.', 'Coulomb = Ampere * segundo.', 'basic', 1140, 'Despeja la carga a partir de la definicion de corriente electrica I = q/t.'))
    return q

def get_questions_campo_electrico_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Carga puntual Q = 5.0 nC crea campo a 0.30 m en el vacio (k=9e9). ¿Modulo de E?', '500 N/C', ['150 N/C', '1500 N/C', '50 N/C'], 'E = 9e9 * 5e-9 / (0.3)^2 = 45 / 0.09 = 500 N/C.', 'E = 500 N/C.', 'basic', 1200, 'Aplica E = k*Q / r^2 dividiendo entre el radio al cuadrado.'))
    q.append(make_mc('Campo electrico uniforme E = 4000 N/C empuja carga q = 2.5 microC. ¿Fuerza electrica?', '0.010 N', ['0.020 N', '0.005 N', '0.040 N'], 'F = q * E = 2.5e-6 * 4000 = 0.010 N.', 'F = 0.010 N.', 'basic', 1180, 'Multiplica la intensidad del campo por la carga electrica.'))
    q.append(make_mc('Un proton (m=1.67e-27 kg, q=1.6e-19 C) en campo E = 2.0e4 N/C. ¿Aceleracion que sufre?', '1.92e12 m/s²', ['3.84e12 m/s²', '9.60e11 m/s²', '1.20e11 m/s²'], 'a = q*E / m = 1.6e-19 * 2e4 / 1.67e-27 = 1.916e12 m/s2.', 'a = 1.92e12 m/s2.', 'intermediate', 1240, 'Calcula la fuerza F = q*E y dividela por la masa del proton.'))
    q.append(make_mc('Dos placas paralelas separadas 0.02 m tienen tension de 200 V. ¿Campo electrico uniforme?', '10000 V/m', ['5000 V/m', '20000 V/m', '4000 V/m'], 'E = Delta V / d = 200 / 0.02 = 10000 V/m.', 'E = 10000 V/m.', 'basic', 1190, 'Divide la diferencia de potencial entre la distancia entre placas.'))
    q.append(make_mc('A que distancia de una carga Q = 4.0 microC el campo vale 9000 N/C en vacio? (k=9e9):', '2.0 m', ['1.0 m', '4.0 m', '0.5 m'], 'r^2 = k*Q / E = 9e9 * 4e-6 / 9000 = 36000 / 9000 = 4 -> r = 2.0 m.', 'r = 2.0 m.', 'intermediate', 1230, 'Despeja r en la formula E = k*Q / r^2 sacando raiz cuadrada.'))
    q.append(make_mc('Gota de masa 3.2e-14 kg flota en equilibrio en campo vertical E = 2.0e5 N/C (g = 10 m/s2). ¿Carga q?', '1.6e-18 C', ['3.2e-18 C', '8.0e-19 C', '6.4e-18 C'], 'q*E = m*g -> q = 3.2e-14 * 10 / 2e5 = 3.2e-13 / 2e5 = 1.6e-18 C.', 'q = 1.6e-18 C.', 'advanced', 1270, 'Iguala la fuerza electrica ascendente con el peso descendente de la gota.'))
    q.append(make_mc('Flujo electrico a traves de una superficie cerrada que encierra carga neta q = 8.85 nC (epsilon_0 = 8.85e-12):', '1000 N·m²/C', ['500 N·m²/C', '2000 N·m²/C', '100 N·m²/C'], 'Ley de Gauss: Phi = q_enc / epsilon_0 = 8.85e-9 / 8.85e-12 = 1000 N*m2/C.', 'Phi = 1000 N*m2/C.', 'intermediate', 1250, 'Aplica la ley de Gauss dividiendo la carga encerrada entre epsilon_0.'))
    q.append(make_mc('Dos cargas iguales de +2.0 microC separadas 2.0 m. ¿Campo electrico en el punto medio exacto?', '0 N/C', ['9000 N/C', '18000 N/C', '36000 N/C'], 'Por simetria, los campos creados son iguales en modulo y sentidos opuestos: E_tot = 0.', 'E = 0 N/C por cancelacion vectorial.', 'basic', 1170, 'Los vectores de campo apuntan alejandose de cada carga: ¿hacia donde van en el punto medio?'))
    q.append(make_mc('En esfera conductora en equilibrio electrostático de radio 0.10 m con carga 20 nC, ¿campo en r = 0.05 m (adentro)?', '0 N/C', ['18000 N/C', '9000 N/C', '36000 N/C'], 'En el interior de cualquier conductor en equilibrio electrostático el campo es estrictamente cero.', 'E = 0 en el interior del conductor.', 'basic', 1180, 'Recuerda el comportamiento del campo electrico estatico dentro de un metal.'))
    q.append(make_mc('Particula alfa (q = +2e) entra en campo E uniforme de 5000 N/C. ¿Modulo de la fuerza electrica?', '1.6e-15 N', ['8.0e-16 N', '3.2e-15 N', '4.0e-16 N'], 'F = q*E = 2 * 1.6e-19 * 5000 = 1.6e-15 N.', 'F = 1.6e-15 N.', 'intermediate', 1220, 'Multiplica dos cargas elementales por la intensidad del campo electrico.'))
    # Teoricas
    q.append(make_mc('El campo electrico E en un punto del espacio se define operacionalmente como:', 'La fuerza sobre una carga de prueba positiva dividida entre dicha carga', ['El trabajo necesario para mover una carga unitaria al infinito', 'La variacion temporal del potencial electrostatico vectorial', 'La cantidad neta de carga encerrada en una superficie gaussiana'], 'E = lim F / q_0 cuando q_0 tiende a cero.', 'E = F / q_0.', 'basic', 1160, '¿Que razon de fuerza por unidad de carga define la intensidad de campo?'))
    q.append(make_mc('Las lineas de campo electrico nunca pueden cruzarse en el espacio porque:', 'El campo tendria dos direcciones distintas en un mismo punto', ['La intensidad del campo se volveria infinita en el cruce', 'Las cargas se neutralizarian al tocarse las lineas', 'El flujo electrico a traves de la zona se haria negativo'], 'El vector E es unico y tangente a la linea en cada punto.', 'E tendria dos direcciones simultaneas, lo cual es imposible.', 'basic', 1170, 'El campo electrico es una funcion vectorial univoca en cada posicion.'))
    q.append(make_mc('En el interior de un conductor en equilibrio electrostatico, el campo electrico:', 'Es estrictamente nulo en todos sus puntos internos', ['Es maximo en el centro geometrico del material', 'Aumenta linealmente desde el centro a la periferia', 'Depende de la permeabilidad magnetica del metal'], 'Si hubiera campo interno, los electrones libres se moverian, no habria equilibrio.', 'E = 0 en el interior del conductor en equilibrio.', 'basic', 1170, 'Si hubiera campo electrico interno, ¿estarian las cargas en reposo?'))
    q.append(make_mc('Toda la carga neta de un conductor en equilibrio electrostatico reside en:', 'Su superficie exterior exclusivamente', ['El centro geometrico del conductor solido', 'Distribuida uniformemente por todo el volumen', 'En los puntos de menor curvatura geometrica'], 'Por repulsion mutua, las cargas se alojan en la frontera externa.', 'Toda la carga reside en la superficie exterior.', 'basic', 1180, '¿Hacia donde empuja la repulsion mutua a las cargas libres del metal?'))
    q.append(make_mc('El fenomeno del efecto de las puntas en conductores cargados se debe a que:', 'El campo electrico es mucho mas intenso en zonas de menor radio de curvatura', ['Las puntas concentran electrones de valencia mas pesados', 'El potencial electrico en las puntas es el doble que en la base', 'El aire circundante se comprime fuertemente en las aristas'], 'Menor radio de curvatura implica mayor densidad de carga superficial sigma.', 'Mayor densidad de carga y campo en zonas agudas.', 'intermediate', 1230, '¿Donde se acumula mayor densidad superficial de carga en un conductor irregular?'))
    q.append(make_mc('La Ley de Gauss relaciona el flujo electrico total a traves de una superficie cerrada con:', 'La carga neta total encerrada dividida entre epsilon_0', ['El potencial electrico promedio sobre el area de la superficie', 'La masa total de las cargas que componen el sistema', 'La intensidad de la corriente electrica entrante'], 'Phi_E = Q_encerrada / epsilon_0.', 'Phi = Q_enc / epsilon_0.', 'intermediate', 1220, '¿Que magnitud fisica encerrada determina el flujo neto total?'))
    q.append(make_mc('El campo electrico inmediatamente exterior a la superficie de un conductor cargado es:', 'Perpendicular a la superficie en cada punto', ['Tangente a la superficie del conductor', 'Forma un angulo de 45° con la normal', 'Es estrictamente nulo en el exterior'], 'Si tuviera componente tangencial, habria corriente superficial.', 'E exterior es perpendicular a la superficie.', 'intermediate', 1230, 'Si hubiera componente tangencial, ¿podrian estar las cargas superficiales en reposo?'))
    q.append(make_mc('La jaula de Faraday demuestra el principio de apantallamiento electrostatico, segun el cual:', 'El interior hueco de un conductor queda protegido de campos externos', ['Las ondas sonoras no pueden propagarse en recintos metalicos', 'El voltaje dentro de la jaula se multiplica peligrosamente', 'La carga exterior fluye de inmediato hacia el ocupante'], 'La redistribucion superficial cancela el campo externo en la cavidad.', 'Campo exterior se anula dentro de la cavidad hueca.', 'basic', 1170, '¿Que le ocurre al campo electrico en el interior hueco de una carroceria de auto?'))
    q.append(make_mc('La unidad del campo electrico en el Sistema Internacional puede expresarse indistintamente como:', 'N/C o V/m', ['J/C o W/m', 'N·m o V·s', 'Tesla o Gauss'], '1 N/C = 1 (J/m) / C = 1 (J/C) / m = 1 V/m.', 'N/C o V/m.', 'basic', 1150, 'Relaciona la definicion por fuerza (F/q) con la definicion por voltaje (Delta V / d).'))
    q.append(make_mc('Entre dos placas conductoras paralelas infinitas con densidades de carga opuestas +sigma y -sigma:', 'El campo es uniforme y vale sigma / epsilon_0', ['El campo se duplica en cada placa y se anula al medio', 'El campo decrece con el cuadrado de la separacion', 'El campo es radial convergente al centro geometrico'], 'Los campos de ambas placas se suman uniformemente: sigma / epsilon_0.', 'E = sigma / epsilon_0 uniforme entre placas.', 'advanced', 1260, 'Suma los campos de dos planos cargados de signos opuestos.'))
    return q


def get_questions_potencial_electrico_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Carga puntual Q = 6.0 nC en vacio (k=9e9). ¿Potencial electrostatico a 0.20 m?', '270 V', ['135 V', '540 V', '90 V'], 'V = k*Q / r = 9e9 * 6e-9 / 0.20 = 54 / 0.20 = 270 V.', 'V = 270 V.', 'basic', 1190, 'Aplica la formula V = k*Q / r con el radio lineal.'))
    q.append(make_mc('Trabajo para trasladar q = 3.0 microC entre dos puntos con Delta V = 50 V:', '1.5e-4 J', ['3.0e-4 J', '7.5e-5 J', '1.5e-3 J'], 'W = q * Delta V = 3e-6 * 50 = 1.5e-4 J.', 'W = 1.5e-4 J.', 'basic', 1180, 'Multiplica la carga transportada por la diferencia de potencial.'))
    q.append(make_mc('Campo uniforme E = 2000 V/m. ¿Diferencia de potencial entre dos puntos separados 0.05 m en linea con el campo?', '100 V', ['50 V', '200 V', '40 V'], 'Delta V = E * d = 2000 * 0.05 = 100 V.', 'Delta V = 100 V.', 'basic', 1180, 'Multiplica el campo electrico uniforme por la distancia en su direccion.'))
    q.append(make_mc('Electron (q = -1.6e-19 C) acelerado desde el reposo por Delta V = 500 V. ¿Energia cinetica final?', '500 eV', ['250 eV', '1000 eV', '50 eV'], 'Ek = q * Delta V = 1 e * 500 V = 500 eV = 8.0e-17 J.', 'Ek = 500 eV.', 'basic', 1170, 'Un electron acelerado por un Volt adquiere un electron-Volt de energia.'))
    q.append(make_mc('Energia potencial electrostatica entre dos cargas de 2.0 microC y 5.0 microC a 0.10 m (k=9e9):', '0.90 J', ['0.45 J', '1.80 J', '9.0 J'], 'U = k*q1*q2 / r = 9e9 * 2e-6 * 5e-6 / 0.10 = 0.09 / 0.10 = 0.90 J.', 'U = 0.90 J.', 'intermediate', 1230, 'Divide k por el producto de cargas y entre la distancia simple.'))
    q.append(make_mc('Esfera conductora de radio 0.15 m con carga de 30 nC (k=9e9). ¿Potencial en su superficie?', '1800 V', ['900 V', '3600 V', '2700 V'], 'V = k*Q / R = 9e9 * 30e-9 / 0.15 = 270 / 0.15 = 1800 V.', 'V = 1800 V.', 'intermediate', 1220, 'El potencial en la superficie de la esfera es k*Q / R.'))
    q.append(make_mc('En la misma esfera conductora del ejercicio anterior (R = 0.15 m), ¿potencial en r = 0.05 m (centro)?', '1800 V', ['0 V', '5400 V', '600 V'], 'Todo el volumen de un conductor en equilibrio es equipotencial: V_int = V_sup = 1800 V.', 'V_int = 1800 V.', 'intermediate', 1240, 'Recuerda que dentro del conductor E = 0, por lo que el potencial es constante.'))
    q.append(make_mc('Dos cargas iguales de +4.0 microC separadas 0.40 m. ¿Potencial en el punto medio exacto?', '3.6e5 V', ['1.8e5 V', '0 V', '7.2e5 V'], 'V_tot = 2 * (k*Q / (r/2)) = 2 * (9e9 * 4e-6 / 0.20) = 2 * 1.8e5 = 3.6e5 V.', 'V = 360000 V.', 'intermediate', 1240, 'El potencial es un escalar: se suman algebraicamente los aportes de cada carga.'))
    q.append(make_mc('¿Que velocidad adquiere un proton (m=1.67e-27 kg, q=1.6e-19 C) acelerado por 1000 V desde el reposo?', '4.38e5 m/s', ['2.19e5 m/s', '8.76e5 m/s', '1.09e5 m/s'], '0.5*m*v^2 = q*V -> v = sqrt(2*q*V / m) = sqrt(2 * 1.6e-19 * 1000 / 1.67e-27) = 4.377e5 m/s.', 'v = 4.38e5 m/s.', 'advanced', 1280, 'Iguala la energia potencial electrica cedida a la energia cinetica adquirida.'))
    q.append(make_mc('Diferencia de potencial entre dos superficies equipotenciales es 60 V. Trabajo para mover 0.02 C a lo largo de la misma superficie:', '0.0 J', ['1.2 J', '60 J', '3000 J'], 'Al moverse a lo largo de una equipotencial Delta V = 0 => W = q * 0 = 0.', 'W = 0 sobre una equipotencial.', 'basic', 1160, 'Sobre una superficie equipotencial, ¿cambia el potencial electrico?'))
    # Teoricas
    q.append(make_mc('El potencial electrico V en un punto es una magnitud de naturaleza:', 'Escalar que representa energia por unidad de carga', ['Vectorial tangente a las lineas de fuerza', 'Tensorial dependiente del area de prueba', 'Adimensional en el Sistema Internacional'], 'V = U / q es escalar medido en Joules por Coulomb (Volts).', 'V es una magnitud escalar.', 'basic', 1150, '¿Tiene el potencial electrico una direccion espacial como una flecha?'))
    q.append(make_mc('Una superficie equipotencial se define como el conjunto de puntos donde:', 'El potencial electrostatico tiene exactamente el mismo valor', ['El campo electrico tiene intensidad estrictamente nula', 'La carga electrica acumulada es maxima absoluta', 'Las lineas de campo son paralelas a la superficie'], 'Equipotencial: Delta V = 0 entre cualesquiera dos puntos.', 'Mismo valor de potencial en todos sus puntos.', 'basic', 1150, 'El prefijo equi denota igualdad de potencial.'))
    q.append(make_mc('Las lineas de campo electrico y las superficies equipotenciales:', 'Son perpendiculares entre si en todos los puntos', ['Son paralelas entre si en todos los puntos', 'Forman angulos agudos de 45 grados', 'Coinciden en la misma orientacion espacial'], 'E apunta en la direccion de maximo descenso de V, normal a las equipotenciales.', 'Son siempre perpendiculares entre si.', 'basic', 1170, '¿Como se cortan las lineas de fuerza con las superficies de igual voltaje?'))
    q.append(make_mc('Al desplazarse en el mismo sentido que las lineas de campo electrico, el potencial:', 'Disminuye progresivamente', ['Aumenta progresivamente', 'Permanece estrictamente constante', 'Oscila entre maximos y minimos'], 'Las lineas de campo apuntan hacia potenciales decrecientes: E = - grad V.', 'El potencial disminuye a favor de E.', 'intermediate', 1210, '¿Hacia donde se mueven espontaneamente las cargas positivas liberadas en el campo?'))
    q.append(make_mc('Un conductor en equilibrio electrostático constituye una region:', 'Completamente equipotencial en volumen y superficie', ['Con mayor potencial en el centro que en la piel', 'Con potencial nulo unicamente en las puntas', 'Con voltaje dependiente de la densidad de masa'], 'Como E = 0 en el interior, no hay variacion de potencial: V = cte.', 'El conductor completo es un cuerpo equipotencial.', 'intermediate', 1220, 'Si el campo electrico interno es cero, ¿puede haber diferencia de potencial?'))
    q.append(make_mc('El trabajo realizado por el campo electrostatico sobre una carga en una trayectoria cerrada:', 'Es estrictamente nulo por ser campo conservativo', ['Es maximo positivo proporcional al perimetro', 'Depende de la velocidad a la que se recorra', 'Depende de la presencia de dielectricos externos'], 'El campo electrostatico es conservativo: integral de linea cerrada es cero.', 'W = 0 en trayectorias cerradas (conservativo).', 'intermediate', 1230, '¿Como se comporta el trabajo de una fuerza conservativa en un ciclo cerrado?'))
    q.append(make_mc('La unidad del Sistema Internacional para el potencial electrico es el Volt (V), igual a:', 'Joule sobre Coulomb (J/C)', ['Newton por metro cuadrado', 'Coulomb por segundo (C/s)', 'Watt sobre Ampere cuadrado'], '1 V = 1 J / 1 C.', 'Volt = Joule / Coulomb.', 'basic', 1140, 'Recuerda que el potencial mide la energia por cada unidad de carga transportada.'))
    q.append(make_mc('El electron-volt (eV) es una unidad utilizada comunmente para medir:', 'Energia en fisica atomica y nuclear', ['Diferencia de potencial en aceleradores', 'Intensidad de corriente electronica', 'Carga electrica fraccionaria de quarks'], '1 eV = 1.602e-19 J: unidad de energia.', 'Unidad de energia (1 eV = 1.6e-19 J).', 'basic', 1160, 'Distingue entre la unidad de potencial (Volt) y la de energia (electron-Volt).'))
    q.append(make_mc('Si se traslada una carga testigo entre dos puntos a traves de tres caminos diferentes en un campo estatico:', 'El trabajo realizado es identico en los tres caminos', ['El camino mas corto realiza menor trabajo que los demas', 'El camino con mas curvas consume mayor trabajo neto', 'El trabajo solo existe si la trayectoria es recta'], 'El trabajo es independiente de la trayectoria por ser campo conservativo.', 'Trabajo independiente del camino seguido.', 'intermediate', 1220, '¿Depende el trabajo de una fuerza conservativa del recorrido o solo de los extremos?'))
    q.append(make_mc('La conexion a tierra de un circuito o chasis metalico se define como fijar:', 'El potencial de referencia a cero Volts (V = 0)', ['La corriente total a un valor maximo infinito', 'La resistencia del equipo a un valor infinito', 'El campo electrostatico a 1000 N/C constante'], 'La Tierra actua como reservorio infinito de carga a potencial nulo.', 'Fija el potencial de referencia en cero.', 'basic', 1150, '¿Que nivel de potencial de referencia se toma convencionalmente en el suelo?'))
    return q

def get_questions_circuitos_corriente_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Alambre de cobre (rho = 1.7e-8 ohm·m) tiene L = 50 m y seccion A = 1.0 mm2. ¿Resistencia R?', '0.85 ohm', ['1.70 ohm', '0.43 ohm', '8.50 ohm'], 'R = rho * L / A = 1.7e-8 * 50 / 1e-6 = 0.85 ohm.', 'R = 0.85 ohm.', 'basic', 1200, 'Aplica la ley de Pouillet pasando los milimetros cuadrados a metros cuadrados.'))
    q.append(make_mc('Por conductor circula corriente de 2.5 A durante 4.0 minutos. ¿Cuanta carga paso?', '600 C', ['10 C', '300 C', '1200 C'], 'q = I * t = 2.5 * (4 * 60) = 2.5 * 240 = 600 C.', 'q = 600 C.', 'basic', 1160, 'Convierte los minutos a segundos antes de multiplicar por la corriente.'))
    q.append(make_mc('Alambre de cobre se estira al doble de su longitud original conservando el volumen. Su nueva resistencia:', 'Se cuadruplica (4R)', ['Se duplica (2R)', 'Permanece igual (R)', 'Se reduce a R/2'], 'L se duplica y A se reduce a la mitad: R_nueva = rho*(2L)/(A/2) = 4R.', 'R se cuadruplica (factor 4).', 'intermediate', 1250, 'Si el alambre se estira al doble, ¿que ocurre con su seccion transversal?'))
    q.append(make_mc('Calefactor de 2200 W funciona a 220 V. ¿Cual es su resistencia electrica interna?', '22 ohms', ['10 ohms', '44 ohms', '100 ohms'], 'R = V^2 / P = 220^2 / 2200 = 48400 / 2200 = 22 ohms.', 'R = 22 ohms.', 'intermediate', 1210, 'Usa la formula que vincula la resistencia con la tension al cuadrado y la potencia.'))
    q.append(make_mc('Cable con seccion 2.0 mm2 lleva corriente de 10 A. ¿Densidad de corriente J?', '5.0 A/mm²', ['0.2 A/mm²', '20 A/mm²', '2.5 A/mm²'], 'J = I / A = 10 / 2.0 = 5.0 A/mm2 = 5e6 A/m2.', 'J = 5 A/mm².', 'basic', 1170, 'Divide la corriente total entre la seccion transversal del cable.'))
    q.append(make_mc('Bateria de 12 V con resistencia interna r = 0.5 ohm entrega corriente de 4.0 A. ¿Voltaje en bornes?', '10.0 V', ['12.0 V', '11.0 V', '8.0 V'], 'V_bornes = fem - I*r = 12 - 4.0 * 0.5 = 12 - 2 = 10 V.', 'V = 10 V.', 'intermediate', 1230, 'Resta la caida de tension interna I*r de la fuerza electromotriz.'))
    q.append(make_mc('Ducha electrica de 4400 W conectada a 220 V se usa 15 min diarios. ¿Energia consumida al mes (30 dias)?', '33 kWh', ['66 kWh', '22 kWh', '11 kWh'], 't_tot = 30 * 0.25 h = 7.5 h. E = 4.4 kW * 7.5 h = 33 kWh.', 'E = 33 kWh.', 'intermediate', 1220, 'Calcula las horas mensuales totales y multiplicalas por los kilowatts.'))
    q.append(make_mc('Conductor tiene resistencia de 100 ohms a 20°C y coeficiente alfa = 0.004 °C^-1. ¿Resistencia a 70°C?', '120 ohms', ['110 ohms', '140 ohms', '105 ohms'], 'R = R0 * (1 + alfa * Delta T) = 100 * (1 + 0.004 * 50) = 100 * 1.20 = 120 ohms.', 'R = 120 ohms.', 'intermediate', 1240, 'Aplica la variacion termica lineal de la resistencia metalica.'))
    q.append(make_mc('¿Cuantos electrones atraviesan un foco cada segundo cuando circula corriente de 0.80 A? (e = 1.6e-19 C)', '5.0e18 electrones', ['2.5e18 electrones', '1.0e19 electrones', '8.0e18 electrones'], 'N = I / e = 0.80 / 1.6e-19 = 5.0e18 electrones/s.', 'N = 5.0e18 electrones/s.', 'basic', 1190, 'Divide la corriente entre el valor de la carga de un electron.'))
    q.append(make_mc('Corriente de 3.0 A fluye por resistencia de 10 ohms durante 20 segundos. ¿Calor generado (Joule)?', '1800 J', ['600 J', '900 J', '3600 J'], 'Q = I^2 * R * t = 9 * 10 * 20 = 1800 J.', 'Q = 1800 J.', 'intermediate', 1210, 'Aplica la ley de Joule multiplicando I al cuadrado por R y por el tiempo.'))
    # Teoricas
    q.append(make_mc('La intensidad de corriente electrica se define formalmente como:', 'La tasa temporal a la que la carga neta fluye a traves de una seccion transversal', ['La velocidad a la que viajan las ondas electromagneticas por el cable', 'La fuerza de atraccion entre los electrones de valencia y el nucleo', 'La potencia disipada por unidad de volumen en el conductor'], 'I = dq / dt: flujo de carga por unidad de tiempo.', 'dq / dt a traves de una seccion.', 'basic', 1160, '¿Que derivada temporal de carga describe la corriente electrica?'))
    q.append(make_mc('El sentido convencional de la corriente electrica se asume por tradicion como:', 'El sentido del movimiento de cargas positivas imaginarias', ['El sentido real en que viajan los electrones de valencia', 'Siempre en sentido antihorario en cualquier circuito', 'Hacia el borne de menor potencial electrico siempre'], 'Sentido historico de Ben Franklin: de mayor a menor potencial (+ a -).', 'Sentido de las cargas positivas imaginarias.', 'basic', 1150, '¿Hacia donde se moverian las cargas de prueba positivas en el circuito?'))
    q.append(make_mc('La velocidad de arrastre o deriva promedio de los electrones en un cable tipico es:', 'Muy lenta, del orden de fracciones de milimetro por segundo', ['Cercana a la velocidad de la luz en el vacio (300.000 km/s)', 'Igual a la rapidez del sonido en el metal solido', 'Instantanea e infinita en todo el trayecto'], 'Los electrones derivan muy lentamente (aprox 0.1 mm/s) por continuas colisiones.', 'Muy lenta (fracciones de mm/s).', 'intermediate', 1240, 'Distingue entre la velocidad del pulso electromagnetico y la deriva de masa de electrones.'))
    q.append(make_mc('La Ley de Pouillet indica que la resistencia R de un conductor homogeneo es:', 'Directamente proporcional a su longitud e inversamente a su seccion', ['Inversamente proporcional a la longitud y directa a la seccion', 'Directamente proporcional al cuadrado del voltaje aplicado', 'Independiente de la temperatura y de la geometria del cable'], 'R = rho * L / A.', 'Directa a longitud e inversa a seccion.', 'basic', 1160, 'Fijate en que variables van en el numerador y denominador de Pouillet.'))
    q.append(make_mc('Los materiales ohmicos se caracterizan porque:', 'La razon V / I es constante en un amplio rango de voltajes', ['Su resistencia cae a cero absoluto al elevar la corriente', 'Solo conducen electricidad en un unico sentido preferencial', 'Su resistividad depende cuadraticamente del voltaje'], 'Ley de Ohm macroscopica: V = I * R con R constante.', 'R constante independientemente de V e I.', 'basic', 1160, 'En una grafica V versus I, ¿que forma tiene la curva de un material ohmico?'))
    q.append(make_mc('La fuerza electromotriz (fem) de una fuente de alimentacion representa:', 'La energia por unidad de carga que la fuente suministra al circuito', ['La fuerza electrostatica neta ejercida sobre los bornes', 'La potencia maxima disipada en forma de calor interno', 'La corriente de cortocircuito entregada al exterior'], 'fem = dW_quimico / dq en Volts (J/C).', 'Energia por unidad de carga suministrada.', 'intermediate', 1220, '¿Que magnitud energetica por unidad de carga eleva el potencial en la pila?'))
    q.append(make_mc('Al aumentar la temperatura de un metal conductor tipico, su resistividad:', 'Aumenta debido a la mayor vibracion de los iones de la red', ['Disminuye porque los electrones ganan mayor velocidad', 'Permanece fija al ser propiedad invariable de la materia', 'Cae a cero convirtiendo al metal en superconductor'], 'Mayor agitacion termica de los iones provoca mas colisiones con electrones.', 'Aumenta por mayor choque con iones termicos.', 'intermediate', 1230, '¿Tienen los electrones mas colisiones cuando la red cristalina vibra mas rapido?'))
    q.append(make_mc('Un superconductor es un material especial que a temperaturas muy bajas exhibe:', 'Resistencia electrica exactamente nula y expulsion de campo magnetico', ['Resistencia electrica infinita que impide todo flujo de carga', 'Capacidad de generar voltaje espontaneo sin bateria', 'Atraccion electrostatica permanente hacia los dielectricos'], 'A temperatura critica Tc la resistencia cae estrictamente a cero (efecto Meissner).', 'Resistencia nula por debajo de Tc.', 'intermediate', 1230, '¿Que valor toma la resistencia en el estado de superconductividad?'))
    q.append(make_mc('La potencia electrica disipada en un resistor puramente ohmico se expresa como:', 'P = V * I = I² * R = V² / R', ['P = V / I = I / R = R / V²', 'P = V * R * t = I * t / R', 'P = I * R² = V² * I'], 'Formulaciones equivalentes del efecto Joule en resistores.', 'P = V*I = I²*R = V²/R.', 'basic', 1150, 'Combina la definicion de potencia P = V*I con la Ley de Ohm V = I*R.'))
    q.append(make_mc('El kilowatt-hora (kWh) es una unidad comercial utilizada para medir:', 'Energia electrica consumida', ['Potencia electrica instantanea', 'Intensidad de corriente media', 'Tension eficaz de distribucion'], '1 kWh = 1000 W * 3600 s = 3.6e6 J (Joules de energia).', 'Unidad de energia (3.6 MegaJoules).', 'basic', 1140, 'Multiplica potencia (kW) por tiempo (h) para obtener la magnitud fisica real.'))
    return q

def get_questions_kirchhoff_extra():
    q = []
    # Ejercicios
    q.append(make_mc('A un nodo ingresan corrientes I1 = 4.0 A e I2 = 3.0 A. Si sale I3 = 2.0 A, ¿cuanto vale la otra corriente saliente I4?', '5.0 A', ['7.0 A', '1.0 A', '9.0 A'], 'LCK: 4 + 3 = 2 + I4 -> 7 = 2 + I4 -> I4 = 5.0 A.', 'I4 = 5 A.', 'basic', 1180, 'Aplica la Primera Ley de Kirchhoff: suma de corrientes entrantes igual a salientes.'))
    q.append(make_mc('Malla simple tiene bateria de 18 V y dos resistencias en serie de 4 ohms y 5 ohms. ¿Corriente de malla?', '2.0 A', ['1.0 A', '3.0 A', '4.5 A'], 'I = E / (R1 + R2) = 18 / (4 + 5) = 18 / 9 = 2.0 A.', 'I = 2 A.', 'basic', 1170, 'Divide la fem total entre la suma de resistencias de la malla.'))
    q.append(make_mc('Circuito con dos baterias opuestas en serie de 12 V y 4 V con resistencia total de 4 ohms. ¿Corriente?', '2.0 A', ['4.0 A', '1.0 A', '3.0 A'], 'fem_neta = 12 - 4 = 8 V. I = 8 / 4 = 2.0 A.', 'I = 2 A.', 'intermediate', 1210, 'Resta las fuerzas electromotrices opuestas antes de aplicar Ohm.'))
    q.append(make_mc('Rama en paralelo tiene R1 = 20 ohms con I1 = 3.0 A. ¿Corriente I2 en R2 = 30 ohms en paralelo?', '2.0 A', ['3.0 A', '4.5 A', '1.5 A'], 'V = I1 * R1 = 3 * 20 = 60 V. I2 = 60 / 30 = 2.0 A.', 'I2 = 2 A.', 'intermediate', 1220, 'Al estar en paralelo comparten el mismo voltaje entre sus bornes.'))
    q.append(make_mc('En una malla, recorriendo en sentido horario: fem = +24 V, caida I*R1 = -10 V, caida I*R2 = -8 V. ¿Voltaje en el 3er resistor?', '6.0 V', ['12.0 V', '4.0 V', '8.0 V'], 'LTK: 24 - 10 - 8 - V3 = 0 -> V3 = 6.0 V.', 'V3 = 6 V.', 'basic', 1190, 'Aplica la Segunda Ley de Kirchhoff: la suma algebraica de tensiones en la malla es cero.'))
    q.append(make_mc('Tres ramas en paralelo reciben tension de 12 V con R = 6, 12 y 4 ohms. ¿Corriente total de la bateria?', '6.0 A', ['4.0 A', '8.0 A', '3.0 A'], 'I_tot = 12/6 + 12/12 + 12/4 = 2 + 1 + 3 = 6.0 A.', 'I = 6 A.', 'intermediate', 1220, 'Calcula la corriente de cada rama individual y sumalas segun la LCK.'))
    q.append(make_mc('Puente de Wheatstone en equilibrio tiene R1 = 10 ohms, R2 = 20 ohms, R3 = 15 ohms. ¿Valor de Rx?', '30 ohms', ['25 ohms', '7.5 ohms', '45 ohms'], 'Equilibrio: R1 / R2 = R3 / Rx -> 10 / 20 = 15 / Rx -> Rx = 30 ohms.', 'Rx = 30 ohms.', 'intermediate', 1250, 'Aplica la condicion de equilibrio del puente igualando el producto de ramas cruzadas.'))
    q.append(make_mc('Bateria de 10 V con r = 1 ohm conectada a carga R = 4 ohms. ¿Potencia disipada en la carga R?', '16 W', ['20 W', '25 W', '12 W'], 'I = 10 / (4+1) = 2 A. P_R = I^2 * R = 4 * 4 = 16 W.', 'P = 16 W.', 'intermediate', 1240, 'Calcula la corriente de malla y aplicala a P = I^2 * R.'))
    q.append(make_mc('A un nodo convergen 5 corrientes: tres entran (2 A, 4 A, 5 A) y una sale (3 A). ¿La quinta corriente?', 'Sale con 8.0 A', ['Entra con 8.0 A', 'Sale con 4.0 A', 'Entra con 2.0 A'], 'Entran: 2+4+5 = 11 A. Salen: 3 + I5 -> I5 = 11 - 3 = 8.0 A (sale).', 'I5 = 8 A saliendo.', 'basic', 1180, 'La suma de las que entran debe compensarse exactamente con las que salen.'))
    q.append(make_mc('Circuito divisor de tension con R1 = 1000 ohms y R2 = 2000 ohms conectado a 9.0 V. ¿Voltaje sobre R2?', '6.0 V', ['3.0 V', '4.5 V', '2.0 V'], 'V2 = 9 * 2000 / (1000 + 2000) = 9 * 2/3 = 6.0 V.', 'V2 = 6 V.', 'basic', 1180, 'Aplica la regla del divisor de tension proporcional al valor de R2.'))
    # Teoricas
    q.append(make_mc('La Primera Ley de Kirchhoff (Ley de Nodos o LCK) es una consecuencia directa de:', 'El principio de conservacion de la carga electrica', ['El principio de conservacion de la energia mecanica', 'La conservacion del momento angular dipolar', 'El segundo principio de la termodinamica clasica'], 'En un nodo no puede crearse ni acumularse carga estatica.', 'Conservacion de la carga electrica.', 'basic', 1160, '¿Que magnitud fisica fundamental no puede desaparecer ni acumularse en un empalme?'))
    q.append(make_mc('La Segunda Ley de Kirchhoff (Ley de Mallas o LTK) es una consecuencia directa de:', 'El principio de conservacion de la energia electrica', ['La conservacion de la masa inercial relativista', 'El teorema de Gauss para campos magneticos', 'La ley de induccion mutua de Faraday-Lenz'], 'El trabajo neto al recorrer un lazo cerrado completo es cero.', 'Conservacion de la energia.', 'basic', 1160, 'Al dar una vuelta completa y volver al mismo potencial, ¿que magnitud se conserva?'))
    q.append(make_mc('En la convencion de signos de Kirchhoff al recorrer una malla en el sentido de la corriente I:', 'La caida de potencial en un resistor R tiene signo negativo (-I·R)', ['La caida de potencial en un resistor tiene signo positivo (+I·R)', 'La caida de potencial se vuelve siempre cero absoluto', 'El signo depende exclusivamente de la temperatura'], 'Al ir a favor de la corriente el potencial disminuye: -I*R.', 'Disminucion de potencial: signo negativo (-I*R).', 'intermediate', 1230, '¿El potencial sube o cae al atravesar una resistencia en el sentido de la corriente?'))
    q.append(make_mc('Al atravesar una fuente de tension fem desde el borne negativo (-) hacia el positivo (+):', 'El potencial aumenta, computandose con signo positivo (+E)', ['El potencial disminuye, computandose con signo negativo (-E)', 'La diferencia de potencial es nula por ser interna', 'El signo depende del valor de la resistencia de carga'], 'Pasar de - a + representa una elevacion de potencial (+fem).', 'Elevacion de potencial: signo positivo (+E).', 'basic', 1170, '¿El borne positivo esta a mayor o menor potencial que el borne negativo?'))
    q.append(make_mc('Un nodo en un circuito electrico se define rigurosamente como:', 'Un punto donde confluyen tres o mas conductores o ramas', ['Cualquier conexion entre dos componentes en linea', 'El borne positivo de la bateria principal', 'La conexion a tierra del chasis de proteccion'], 'Nodo principal: punto de union de tres o mas ramas.', 'Confluencia de 3 o mas ramas.', 'basic', 1160, '¿Cuantos cables como minimo deben unirse para que haya ramificacion de corriente?'))
    q.append(make_mc('Una malla en una red electrica se define como:', 'Cualquier trayectoria cerrada que no pase dos veces por el mismo nodo', ['Una sola rama lineal comprendida entre dos nodos', 'El conjunto de todos los resistores conectados en serie', 'El cable que une el neutro con la jabalina de tierra'], 'Malla o lazo: camino cerrado en el grafo del circuito.', 'Trayectoria cerrada en el circuito.', 'basic', 1150, '¿Que recorrido describe una trayectoria que parte de un nodo y regresa a el?'))
    q.append(make_mc('El Teorema de Maxima Transferencia de Potencia indica que una fuente entrega maxima potencia a la carga cuando:', 'La resistencia de carga R es igual a la resistencia interna r de la fuente', ['La resistencia de carga es igual a cero (cortocircuito)', 'La resistencia de carga es infinitamente grande', 'La resistencia interna de la fuente es el doble de la carga'], 'R_carga = R_interna maximiza la potencia transferida.', 'R_carga = R_interna.', 'intermediate', 1240, '¿Que relacion debe haber entre la resistencia del aparato y la interna de la pila?'))
    q.append(make_mc('Para resolver un circuito con N nodos y B ramas mediante el metodo de Kirchhoff, se requieren:', 'N - 1 ecuaciones de nodo independientes', ['N ecuaciones de nodo completamente independientes', 'B + N ecuaciones de nodo simultaneas', 'Exactamente dos ecuaciones sin importar el circuito'], 'En un grafo plano con N nodos, solo N-1 ecuaciones LCK son independientes.', 'N - 1 ecuaciones de nodo independientes.', 'advanced', 1270, 'La ultima ecuacion de nodo siempre es combinacion lineal de las anteriores.'))
    q.append(make_mc('Un cortocircuito ideal en un tramo de circuito se caracteriza por tener:', 'Resistencia nula y corriente limitada solo por el resto del circuito', ['Resistencia infinita y corriente nula permanente', 'Diferencia de potencial maxima igual a 1000 Volts', 'Potencia nula absorbida sin calentamiento'], 'R = 0 provoca circulacion de corrientes muy elevadas.', 'Resistencia cero y caida de tension nula.', 'basic', 1160, '¿Que valor de resistencia ofrece un cable ideal sin carga que une dos bornes?'))
    q.append(make_mc('Un circuito abierto se caracteriza por presentar:', 'Resistencia infinita y corriente estrictamente nula', ['Resistencia nula y corriente extremadamente alta', 'Voltaje nulo entre sus terminales desconectados', 'Potencia disipada maxima en el aislamiento'], 'R -> infinito impide todo flujo de electrones (I = 0).', 'Resistencia infinita y corriente nula.', 'basic', 1150, 'Si un interruptor esta abierto, ¿puede circular corriente a traves de el?'))
    return q


def get_questions_campo_magnetico_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Conductor recto largo con I = 10 A. ¿Campo B a r = 0.05 m? (mu_0 = 4*pi*1e-7)', '4.0e-5 T', ['2.0e-5 T', '8.0e-5 T', '1.0e-5 T'], 'B = mu_0 * I / (2*pi*r) = 4.0e-5 T.', 'B = 4.0e-5 T.', 'basic', 1210, 'Aplica la ley de Biot-Savart para un alambre recto infinito.'))
    q.append(make_mc('Espira circular de radio 0.10 m con I = 5.0 A. ¿Campo B en el centro? (mu_0 = 4*pi*1e-7)', '3.14e-5 T', ['1.57e-5 T', '6.28e-5 T', '3.14e-4 T'], 'B = mu_0 * I / (2*R) = 3.14e-5 T.', 'B = 3.14e-5 T.', 'intermediate', 1230, 'Divide mu_0 por la corriente y entre el doble del radio.'))
    q.append(make_mc('Solenoide de 500 espiras y longitud 0.25 m con I = 2.0 A (mu_0 = 4*pi*1e-7). ¿Campo B?', '5.03e-3 T', ['2.51e-3 T', '1.01e-2 T', '5.03e-4 T'], 'B = mu_0 * (N/L) * I = 5.03e-3 T.', 'B = 5.03 mT.', 'intermediate', 1240, 'Multiplica la densidad de espiras por mu_0 e I.'))
    q.append(make_mc('A que distancia de un cable con I = 20 A el campo B vale 1.0e-4 T? (mu_0 = 4*pi*1e-7)', '0.04 m', ['0.02 m', '0.08 m', '0.10 m'], 'r = mu_0 * I / (2*pi*B) = 0.04 m.', 'r = 0.04 m.', 'basic', 1200, 'Despeja la distancia r en la formula de Biot-Savart.'))
    q.append(make_mc('Flujo magnetico en espira de 0.04 m2 perpendicular a campo uniforme B = 0.50 T:', '0.020 Wb', ['0.010 Wb', '0.040 Wb', '0.080 Wb'], 'Phi = B * A = 0.50 * 0.04 = 0.020 Wb.', 'Phi = 0.020 Wb.', 'basic', 1190, 'Multiplica campo por area transversal.'))
    q.append(make_mc('Dos cables paralelos separados 0.10 m llevan 5.0 A en el mismo sentido. ¿Fuerza por metro?', '5.0e-5 N/m', ['2.5e-5 N/m', '1.0e-4 N/m', '5.0e-6 N/m'], 'F/L = mu_0*I1*I2 / (2*pi*d) = 5.0e-5 N/m.', 'F/L = 5.0e-5 N/m.', 'intermediate', 1250, 'Aplica la formula de fuerza entre corrientes paralelas.'))
    q.append(make_mc('Bobina de 200 vueltas de radio 0.05 m con I = 1.0 A. ¿Campo B en el centro?', '2.51e-3 T', ['1.26e-3 T', '5.03e-3 T', '2.51e-4 T'], 'B = N * mu_0 * I / (2*R) = 2.51e-3 T.', 'B = 2.51 mT.', 'intermediate', 1240, 'Multiplica el campo de una espira por las 200 vueltas.'))
    q.append(make_mc('En un iman recto, la intensidad del campo magnetico es maxima en:', 'Los polos norte y sur exteriores', ['El punto medio geometrico del iman', 'Una distancia de 1 metro del cuerpo', 'Es estrictamente constante'], 'Las lineas se concentran fuertemente en los polos.', 'Maxima densidad en los polos.', 'basic', 1150, '¿Donde emergen y convergen las lineas de un iman?'))
    q.append(make_mc('Campo B terrestre tipico de 50 microTesla. En unidades Gauss equivale a:', '0.5 Gauss', ['5.0 Gauss', '0.05 Gauss', '50 Gauss'], '1 T = 10000 Gauss. 50e-6 * 1e4 = 0.5 Gauss.', '0.5 Gauss.', 'basic', 1160, '1 Tesla equivale a diez mil Gauss.'))
    q.append(make_mc('Flujo magnetico en espira cuando el campo B es paralelo al plano de la espira:', '0.0 Wb', ['B * A', 'B * A / 2', 'Infinito'], 'theta = 90° con la normal: cos(90) = 0.', 'Phi = 0 Wb.', 'basic', 1170, '¿Cuantas lineas atraviesan el area si viajan paralelas al plano?'))
    # Teoricas
    q.append(make_mc('Las lineas de campo magnetico se diferencian de las de campo electrostatico porque:', 'Son siempre lineas cerradas y continuas sin principio ni fin', ['Nacen en cargas positivas y terminan en negativas', 'Tienen extremos abiertos que se proyectan al infinito', 'Nunca pueden rodear a una corriente electrica'], 'div B = 0 implica inexistencia de monopolos magneticos aislados.', 'Lineas siempre cerradas y continuas.', 'basic', 1160, '¿Existen polos magneticos individuales aislados?'))
    q.append(make_mc('La no existencia de monopolos magneticos aislados se traduce en que:', 'Al cortar un iman en dos se obtienen dos imanes completos', ['El iman pierde inmediatamente toda su imantacion', 'Uno de los fragmentos queda como polo norte puro', 'El campo exterior se convierte en campo electrostatico'], 'Siempre coexisten polo norte y polo sur.', 'Se obtienen dos imanes bipolares.', 'basic', 1150, '¿Que sucede al partir un iman por el medio?'))
    q.append(make_mc('La regla de la mano derecha para un conductor rectilineo con corriente establece que:', 'El pulgar apunta en sentido de I y los dedos envuelven indicando el sentido de B', ['El pulgar indica el campo y la palma la corriente electrica', 'El indice apunta a la corriente y el pulgar a la fuerza neta', 'Los cuatro dedos extendidos apuntan siempre hacia el norte'], 'Pulgar = corriente; dedos envolventes = lineas de B.', 'Pulgar = I; dedos envolventes = B.', 'basic', 1150, '¿Como colocas tu mano derecha envolviendo el conductor?'))
    q.append(make_mc('Dos conductores rectilineos paralelos que transportan corrientes en el mismo sentido:', 'Se atraen mutuamente mediante fuerza magnetica', ['Se repelen mutuamente mediante fuerza magnetica', 'No ejercen ninguna fuerza de interaccion mutua', 'Generan una cupla que los hace girar en espiral'], 'Corrientes paralelas de igual sentido se atraen.', 'Se atraen entre si.', 'intermediate', 1210, 'Aplica la regla de la mano derecha y la fuerza sobre corriente.'))
    q.append(make_mc('Un solenoide ideal largo produce en su interior un campo magnetico caracterizado por ser:', 'Uniforme, paralelo a su eje y de intensidad constante', ['Radial con centro en el eje medio del cilindro', 'Nulo en el centro y maximo en los extremos', 'Dependiente del radio de las espiras cilíndricas'], 'B es axial y uniforme en el interior.', 'Campo uniforme y axial.', 'intermediate', 1220, '¿Como son las lineas dentro de una bobina cilíndrica?'))
    q.append(make_mc('La permeabilidad magnetica del vacio mu_0 en el Sistema Internacional tiene el valor exacto:', '4 * pi * 1e-7 T·m/A', ['8.85 * 1e-12 C²/(N·m²)', '9.0 * 1e9 N·m²/C²', '1.60 * 1e-19 C'], 'mu_0 = 4*pi*1e-7 T*m/A.', '4*pi*1e-7 T·m/A.', 'basic', 1150, 'Constante fundamental del magnetismo en el SI.'))
    q.append(make_mc('Un material ferromagnetico como el hierro dulce se caracteriza por:', 'Tener permeabilidad relativa mu_r muy superior a uno y alinearse fuertemente con B', ['Expulsar todo campo magnetico como los diamagneticos', 'No alterar en absoluto las lineas de campo del exterior', 'Tener constante dielectrica nula a temperatura ambiente'], 'Los dominios se alinean intensificando el campo.', 'mu_r >> 1 y fuerte alineacion.', 'intermediate', 1230, '¿Que ocurre con el campo dentro de un nucleo de hierro dulce?'))
    q.append(make_mc('La unidad del Sistema Internacional para el flujo magnetico es el Weber (Wb), igual a:', 'Tesla por metro cuadrado (T·m²)', ['Tesla sobre metro cuadrado (T/m²)', 'Ampere por metro lineal (A/m)', 'Volt por segundo al cuadrado (V·s²)'], '1 Wb = 1 T * 1 m2.', 'Weber = Tesla * m².', 'basic', 1140, 'Multiplica la unidad de campo por la de superficie.'))
    q.append(make_mc('El campo magnetico terrestre actua protegiendo la vida en la Tierra al:', 'Desviar las particulas cargadas daninas del viento solar', ['Filtrar la radiacion infrarroja de la luz diurna', 'Impedir el escape del oxigeno atmosferico al vacio', 'Calentar los oceanos en las regiones polares'], 'La fuerza de Lorentz desvia iones solares peligrosos.', 'Desvia el viento solar ionizado.', 'basic', 1150, '¿Que efecto produce el campo magnetico sobre particulas cargadas?'))
    q.append(make_mc('La Ley de Ampere en su forma clasica establece que la circulacion de B a lo largo de una curva cerrada:', 'Es igual a mu_0 multiplicada por la corriente neta concatenada', ['Es estrictamente nula para cualquier distribucion de corrientes', 'Depende de la variacion temporal del campo electrostatico', 'Es igual a la masa total de los conductores encerrados'], 'Circulacion de B = mu_0 * I_encerrada.', 'mu_0 * I_encerrada.', 'intermediate', 1240, '¿Que corriente debe incluirse en la integral de linea de Ampere?'))
    return q

def get_questions_fuerza_magnetica_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Proton (q = 1.6e-19 C) a 2.0e6 m/s perpendicular a B = 0.50 T. ¿Fuerza magnetica?', '1.6e-13 N', ['3.2e-13 N', '8.0e-14 N', '1.6e-14 N'], 'F = q*v*B = 1.6e-19 * 2e6 * 0.5 = 1.6e-13 N.', 'F = 1.6e-13 N.', 'basic', 1210, 'Aplica F = q*v*B cuando son ortogonales.'))
    q.append(make_mc('Conductor de L = 0.40 m lleva I = 5.0 A perpendicular a B = 0.20 T. ¿Fuerza magnetica?', '0.40 N', ['0.20 N', '0.80 N', '4.0 N'], 'F = I*L*B = 5 * 0.40 * 0.20 = 0.40 N.', 'F = 0.40 N.', 'basic', 1190, 'Aplica la formula de Laplace F = I*L*B.'))
    q.append(make_mc('Electron (m=9.1e-31 kg, q=1.6e-19 C) en B = 0.010 T con v = 3.2e6 m/s. ¿Radio orbital?', '1.82 mm', ['3.64 mm', '0.91 mm', '5.46 mm'], 'R = m*v / (q*B) = 1.82e-3 m = 1.82 mm.', 'R = 1.82 mm.', 'intermediate', 1250, 'Iguala fuerza centripeta a fuerza magnetica y despeja el radio.'))
    q.append(make_mc('Selector de velocidades con E = 60000 V/m y B = 0.20 T cruzados. ¿Velocidad no desviada?', '3.0e5 m/s', ['1.2e5 m/s', '6.0e5 m/s', '1.5e5 m/s'], 'v = E / B = 60000 / 0.20 = 3.0e5 m/s.', 'v = 3.0e5 m/s.', 'intermediate', 1240, 'Iguala q*E con q*v*B y despeja la velocidad.'))
    q.append(make_mc('Particula cargada penetra paralela a las lineas de campo magnetico uniforme. ¿Fuerza?', '0 N', ['q * v * B', 'q * v * B / 2', 'Infinita'], 'F = q*v*B*sen(0) = 0 N.', 'F = 0 N.', 'basic', 1160, 'El seno de cero grados es nulo.'))
    q.append(make_mc('Carga de 2.0 microC a 500 m/s a 30° de B = 0.40 T (sen 30 = 0.50). ¿Modulo de fuerza?', '2.0e-4 N', ['4.0e-4 N', '1.0e-4 N', '3.46e-4 N'], 'F = 2e-6 * 500 * 0.40 * 0.50 = 2.0e-4 N.', 'F = 2.0e-4 N.', 'basic', 1200, 'Multiplica carga, velocidad, campo y sen(30).'))
    q.append(make_mc('Periodo ciclotron de un proton en campo B = 1.0 T (q=1.6e-19 C, m=1.67e-27 kg):', '6.56e-8 s', ['3.28e-8 s', '1.31e-7 s', '6.56e-7 s'], 'T = 2*pi*m / (q*B) = 6.56e-8 s.', 'T = 6.56e-8 s.', 'advanced', 1270, 'El periodo ciclotron T = 2*pi*m / (q*B) es constante.'))
    q.append(make_mc('Espira rectangular de 0.10 m x 0.20 m con I = 2.0 A en B = 0.50 T paralelo. ¿Torque?', '0.020 N·m', ['0.040 N·m', '0.010 N·m', '0.080 N·m'], 'tau = I*A*B = 2.0 * 0.02 * 0.50 = 0.020 N*m.', 'tau = 0.020 N·m.', 'intermediate', 1240, 'Multiplica corriente, area y campo magnetico.'))
    q.append(make_mc('Si una particula duplica su rapidez al entrar perpendicular a B, el radio orbital:', 'Se duplica (2R)', ['Se cuadruplica (4R)', 'Permanece igual (R)', 'Se reduce a R/2'], 'R = m*v / (q*B) es directamente proporcional a v.', 'R se duplica.', 'basic', 1190, 'El radio es directamente proporcional a la velocidad.'))
    q.append(make_mc('Conductor horizontal de 0.20 kg y L = 0.50 m en B = 0.20 T perpendicular (g = 10 m/s2). ¿Corriente?', '20 A', ['10 A', '40 A', '5 A'], 'I = m*g / (L*B) = 2.0 / 0.10 = 20 A.', 'I = 20 A.', 'intermediate', 1250, 'Iguala la fuerza magnetica hacia arriba con el peso.'))
    # Teoricas
    q.append(make_mc('La fuerza magnetica sobre una particula cargada es estrictamente nula cuando:', 'La particula esta en reposo o viaja paralela al campo B', ['La particula viaja a la velocidad de la luz en vacio', 'La masa de la particula es sumamente grande', 'El campo magnetico tiene valor superior a un Tesla'], 'F = q*(v x B). Si v = 0 o v paralelo a B, F = 0.', 'F = 0 si v=0 o paralela a B.', 'basic', 1160, 'El producto vectorial se anula si son paralelos.'))
    q.append(make_mc('El trabajo mecanico realizado por la fuerza magnetica de Lorentz sobre una carga libre es:', 'Siempre estrictamente cero', ['Siempre positivo acelerando a la carga', 'Siempre negativo frenando a la carga', 'Igual a la energia cinetica inicial'], 'F perpendicular a v implica F · v = 0 => W = 0.', 'W = 0 en todo momento.', 'intermediate', 1230, 'Una fuerza perpendicular al desplazamiento no realiza trabajo.'))
    q.append(make_mc('Dado que la fuerza magnetica de Lorentz no realiza trabajo mecanico:', 'Modifica la direccion de la velocidad pero conserva la rapidez', ['Aumenta la energia cinetica sin cambiar la direccion', 'Disminuye la masa inercial de la particula en reposo', 'Frena a la particula hasta dejarla inmóvil en el campo'], 'W = Delta Ek = 0 implica rapidez escalar constante.', 'Rapidez constante, cambia orientacion.', 'intermediate', 1220, 'Al no variar la energia cinetica, la rapidez no cambia.'))
    q.append(make_mc('La regla de la mano derecha para la fuerza de Lorentz F = q(v x B) sobre carga positiva indica:', 'Indice = v, dedos medios = B, pulgar = F', ['Pulgar = v, palma = B, dorso = F', 'Indice = B, pulgar = F, palma = v', 'Cualquier combinacion de dedos'], 'Regla del producto vectorial: dedos v a B, pulgar indica F.', 'Pulgar = F para carga positiva.', 'basic', 1170, '¿Como orientas los dedos en el producto vectorial v cruz B?'))
    q.append(make_mc('Si la particula cargada tiene signo negativo (como un electron), el sentido de la fuerza:', 'Es exactamente opuesto al que predice la regla para carga positiva', ['Es el mismo que para una carga positiva identica', 'Gira noventa grados hacia el vector velocidad', 'Se vuelve nulo al neutralizarse con el campo'], 'q < 0 invierte el sentido del vector fuerza resultante.', 'Sentido opuesto por signo negativo.', 'basic', 1170, 'Invierte la direccion del pulgar para cargas negativas.'))
    q.append(make_mc('Una particula cargada que ingresa con velocidad inclinada oblicua a B describe:', 'Una trayectoria helicoidal (espiral cilindrica)', ['Una circunferencia plana estrictamente cerrada', 'Una linea recta sin ninguna desviacion lateral', 'Una parabola abierta hacia el infinito espacial'], 'La componente paralela avanza en MRU y la perpendicular gira en MCU.', 'Helice cilindrica.', 'intermediate', 1240, 'Combina el avance uniforme longitudinal con el giro circular.'))
    q.append(make_mc('El principio de funcionamiento del motor electrico de corriente continua se basa en:', 'El torque magnetico ejercido sobre una espira con corriente inmersa en B', ['La atraccion electrostatica pura entre placas dielectricas', 'La disipacion de calor Joule en bobinados de alta resistencia', 'El frenado inductivo de corrientes parasitas de Foucault'], 'El par magnetico hace rotar de forma continua el rotor.', 'Torque magnetico sobre espira con corriente.', 'basic', 1170, '¿Que fuerza genera el giro continuo en el rotor del motor?'))
    q.append(make_mc('En un espectrometro de masas tras un selector de velocidades identico:', 'Los iones con mayor relacion masa/carga describen radios mas grandes', ['Todos los isotopos impactan en la misma posicion exacta', 'Los iones mas pesados quedan inmoviles a la entrada', 'Los iones con menor masa describen radios mayores'], 'R = (m/q)*(v/B). A mayor m/q, mayor radio de curvatura.', 'Radio proporcional a relacion m/q.', 'intermediate', 1250, 'Fijate en la relacion directa entre el radio R y la masa m.'))
    q.append(make_mc('La unidad del campo magnetico en el Sistema Internacional es el Tesla (T), igual a:', 'Newton sobre (Ampere·metro) [N/(A·m)]', ['Newton sobre (Coulomb·metro) [N/(C·m)]', 'Volt por metro cuadrado (V·m²)', 'Joule sobre (Ampere·segundo) [J/(A·s)]'], 'F = I*L*B => 1 T = 1 N / (1 A * 1 m).', 'Tesla = N / (A·m).', 'basic', 1150, 'Despeja la unidad de B a partir de F = I*L*B.'))
    q.append(make_mc('El efecto Hall en un conductor con corriente en un campo B transversal produce:', 'Una diferencia de potencial transversal por acumulacion de portadores', ['La duplicacion instantanea de la resistencia electrica del cable', 'La emision espontanea de fotones visibles de fluorescencia', 'El calentamiento uniforme sin perdida de calor al exterior'], 'La fuerza magnetica acumula cargas en una cara creando voltaje Hall.', 'Voltaje transversal por desviacion de portadores.', 'advanced', 1270, '¿Que voltaje transversal surge por la desviacion lateral de portadores?'))
    return q


def get_questions_induccion_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Flujo cambia de 0.80 Wb a 0.20 Wb en 0.20 s en bobina de 100 espiras. ¿fem?', '300 V', ['150 V', '600 V', '60 V'], 'fem = 100 * (0.60 / 0.20) = 300 V.', 'fem = 300 V.', 'basic', 1210, 'Aplica la ley de Faraday N * Delta Phi / Delta t.'))
    q.append(make_mc('Barra de 0.50 m se mueve a 4.0 m/s perpendicular a B = 0.30 T. ¿fem cinetica?', '0.60 V', ['0.30 V', '1.20 V', '0.15 V'], 'fem = B*L*v = 0.30 * 0.50 * 4 = 0.60 V.', 'fem = 0.60 V.', 'basic', 1190, 'Multiplica campo, longitud y velocidad de la barra.'))
    q.append(make_mc('Espira de area 0.05 m2 inmersa en campo variable B(t) = 4.0 * t. ¿fem inducida?', '0.20 V', ['0.10 V', '0.40 V', '0.80 V'], 'fem = A * dB/dt = 0.05 * 4 = 0.20 V.', 'fem = 0.20 V.', 'intermediate', 1230, 'Deriva el flujo multiplicando area por dB/dt.'))
    q.append(make_mc('Bobina con L = 0.50 H experimenta cambio de 4.0 A en 0.02 s. ¿fem autoinducida?', '100 V', ['50 V', '200 V', '25 V'], 'fem = L * Delta I / Delta t = 0.50 * (4 / 0.02) = 100 V.', 'fem = 100 V.', 'intermediate', 1240, 'Multiplica L por la razon de cambio de corriente.'))
    q.append(make_mc('Transformador ideal con Np = 1000 y Ns = 200. Con Vp = 220 V, ¿voltaje secundario?', '44 V', ['1100 V', '88 V', '22 V'], 'Vs = 220 * (200 / 1000) = 44 V.', 'Vs = 44 V.', 'basic', 1180, 'Aplica la relacion de espiras del transformador.'))
    q.append(make_mc('Si en el transformador anterior Ip = 0.50 A, ¿corriente secundaria Is ideal?', '2.5 A', ['0.10 A', '1.0 A', '5.0 A'], 'Vs*Is = Vp*Ip -> 44*Is = 220*0.5 -> Is = 2.5 A.', 'Is = 2.5 A.', 'intermediate', 1230, 'En transformador ideal la potencia se conserva.'))
    q.append(make_mc('Espira cuadrada de 0.10 m de lado sale de B = 0.50 T a v = 2.0 m/s. ¿fem?', '0.10 V', ['0.05 V', '0.20 V', '0.01 V'], 'fem = B*L*v = 0.50 * 0.10 * 2 = 0.10 V.', 'fem = 0.10 V.', 'intermediate', 1220, 'Multiplica B por el lado de la espira y por v.'))
    q.append(make_mc('Energia almacenada en un inductor de L = 0.20 H con I = 5.0 A:', '2.5 J', ['5.0 J', '1.0 J', '0.5 J'], 'U = 0.5 * L * I^2 = 0.5 * 0.20 * 25 = 2.5 J.', 'U = 2.5 J.', 'intermediate', 1230, 'Aplica la formula 0.5 * L * I^2.'))
    q.append(make_mc('Espira gira a 50 rad/s en B = 0.20 T con area A = 0.04 m2. ¿fem maxima?', '0.40 V', ['0.20 V', '0.80 V', '0.08 V'], 'fem_max = omega*B*A = 50 * 0.20 * 0.04 = 0.40 V.', 'fem_max = 0.40 V.', 'intermediate', 1240, 'Multiplica velocidad angular, campo y area.'))
    q.append(make_mc('Flujo magnetico se mantiene constante en 5.0 Wb durante 10 s. ¿fem inducida?', '0.0 V', ['0.5 V', '5.0 V', '50 V'], 'dPhi/dt = 0 implica fem nula.', 'fem = 0 V.', 'basic', 1140, 'Sin variacion temporal de flujo no hay fem inducida.'))
    # Teoricas
    q.append(make_mc('La Ley de Faraday establece que la fem inducida es proporcional a:', 'La rapidez con que cambia el flujo magnetico en el tiempo', ['El valor absoluto del campo magnetico estatico', 'La resistencia electrica de los cables', 'El volumen del iman empleado'], 'fem = - dPhi / dt.', 'Tasa temporal de cambio del flujo.', 'basic', 1160, '¿Que condicion temporal exige Faraday para inducir corriente?'))
    q.append(make_mc('La Ley de Lenz establece que el sentido de la corriente inducida:', 'Se opone a la variacion de flujo que la produce', ['Refuerza el aumento del campo inductor', 'Apunta hacia el polo norte geografico', 'Acelera los conductores'], 'Lenz garantiza la conservacion de la energia.', 'Se opone a la causa que la genera.', 'basic', 1170, '¿Tiende la corriente inducida a frenar o acelerar la variacion?'))
    q.append(make_mc('Si la Ley de Lenz tuviera signo positivo en vez de negativo, se violaria:', 'El principio de conservacion de la energia', ['La relatividad especial de Einstein', 'La conservacion de la carga en los nodos', 'La gravitacion universal de Newton'], 'Generaria energia infinita espontanea.', 'Violaria la conservacion de energia.', 'intermediate', 1230, 'Si reforzara el cambio, ¿creceria la energia indefinidamente?'))
    q.append(make_mc('Las corrientes parasitas de Foucault en masas metalicas en campos variables:', 'Generan calor y un efecto de frenado magnetico', ['Aumentan el rendimiento del transformador', 'Eliminan las perdidas por histeresis', 'Enfrian el nucleo por efecto Peltier'], 'Disipan calor por Joule y crean fuerzas opuestas al movimiento.', 'Disipan calor y generan frenado electromagnetico.', 'intermediate', 1230, '¿Por que se calientan los nucleos macizos en campos alternos?'))
    q.append(make_mc('El nucleo de los transformadores se construye con chapas de hierro laminadas para:', 'Reducir las perdidas de energia por corrientes de Foucault', ['Aumentar la resistencia mecanica contra vibraciones', 'Impedir que el campo escape al exterior', 'Evitar que la corriente pase al chasis'], 'El laminado interrumpe las corrientes en remolino.', 'Reducir perdidas por corrientes parasitas.', 'intermediate', 1240, '¿Que efecto tiene cortar en capas el camino de las corrientes?'))
    q.append(make_mc('Un generador electrico (alternador) convierte directamente:', 'Energia mecanica de rotacion en energia electrica', ['Energia termica en potencial quimica', 'Energia electrostatica en presion hidrostatica', 'Radiacion electromagnetica en calor'], 'El giro mecanico induce corriente alterna.', 'Mecanica a electrica mediante induccion.', 'basic', 1150, '¿Que energia entra a la turbina y cual sale del generador?'))
    q.append(make_mc('Un transformador solo funciona con corriente alterna (CA) porque:', 'Requiere un flujo magnetico continuamente variable', ['La corriente continua quema los bobinados', 'Los electrones de continua no atraviesan el cobre', 'El hierro solo conduce magnetismo a 50 Hz'], 'Con CC dPhi/dt = 0 => fem inducida nula en el secundario.', 'Requiere flujo variable (dPhi/dt != 0).', 'intermediate', 1220, 'Si la corriente es continua pura, ¿varia el flujo en el tiempo?'))
    q.append(make_mc('La inductancia L de una bobina mide formalmente:', 'La oposicion a las variaciones de corriente electrica', ['La maxima carga estatica en sus placas', 'La resistencia ohmica del hilo de cobre', 'El tiempo de calentamiento por Joule'], 'fem_auto = -L * dI/dt.', 'Oposicion al cambio de corriente.', 'intermediate', 1230, 'Es el equivalente electromagnetico a la inercia mecanica.'))
    q.append(make_mc('La unidad de la inductancia en el Sistema Internacional es el Henry (H), igual a:', 'Volt·segundo sobre Ampere (V·s/A)', ['Ohm sobre segundo (Omega/s)', 'Tesla por metro cubico (T·m³)', 'Watt sobre Coulomb (W/C)'], '1 H = 1 V * 1 s / 1 A.', 'Henry = Volt·segundo / Ampere.', 'basic', 1150, 'Despeja L en la ecuacion de autoinduccion de Faraday.'))
    q.append(make_mc('En las cocinas de induccion electromagnetica, la olla se calienta debido a:', 'Corrientes de Foucault inducidas en la base ferromagnetica', ['Resistencias al rojo vivo debajo del vidrio', 'Radiacion de microondas que agita el agua', 'Friccion mecanica ultrasonica'], 'El campo variable induce corrientes parasitas en el fondo de la olla.', 'Corrientes de Foucault en el metal.', 'basic', 1160, '¿Por que no calienta ollas de vidrio o ceramica?'))
    return q

def get_questions_capacitores_rc_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Capacitor de 50 microF conectado a 12 V. ¿Carga acumulada?', '600 microC', ['300 microC', '1200 microC', '50 microC'], 'q = C * V = 50e-6 * 12 = 600 microC.', 'q = 600 microC.', 'basic', 1170, 'Aplica q = C * V.'))
    q.append(make_mc('Circuito RC serie con R = 100 kOhms y C = 20 microF. ¿Constante tau?', '2.0 s', ['0.5 s', '5.0 s', '20.0 s'], 'tau = R * C = 1e5 * 20e-6 = 2.0 s.', 'tau = 2.0 s.', 'basic', 1180, 'Multiplica ohms por faradios.'))
    q.append(make_mc('Energia almacenada en capacitor de 100 microF cargado a 200 V:', '2.0 J', ['4.0 J', '1.0 J', '0.5 J'], 'U = 0.5 * C * V^2 = 0.5 * 100e-6 * 40000 = 2.0 J.', 'U = 2.0 J.', 'intermediate', 1220, 'Aplica 0.5 * C * V al cuadrado.'))
    q.append(make_mc('Dos capacitores de 20 microF y 30 microF en paralelo. ¿Capacidad equivalente?', '50 microF', ['12 microF', '25 microF', '60 microF'], 'C_eq = 20 + 30 = 50 microF.', 'C_eq = 50 microF.', 'basic', 1160, 'En paralelo las capacidades se suman directamente.'))
    q.append(make_mc('Dos capacitores de 20 microF y 30 microF en serie. ¿Capacidad equivalente?', '12 microF', ['50 microF', '25 microF', '10 microF'], 'C_eq = (20 * 30) / (20 + 30) = 12 microF.', 'C_eq = 12 microF.', 'intermediate', 1210, 'Aplica producto sobre suma para dos en serie.'))
    q.append(make_mc('Circuito RC con V0 = 10 V. A t = 1 tau de carga, ¿voltaje en C?', '6.32 V', ['5.00 V', '3.68 V', '9.90 V'], 'Vc = 10 * (1 - e^-1) = 6.32 V (63.2%).', 'Vc = 6.32 V.', 'intermediate', 1230, 'En 1 tau se alcanza el 63.2% de V0.'))
    q.append(make_mc('En descarga de capacitor con V0 = 10 V, a t = 1 tau, ¿voltaje remanente?', '3.68 V', ['6.32 V', '5.00 V', '1.35 V'], 'Vc = 10 * e^-1 = 3.68 V (36.8%).', 'Vc = 3.68 V.', 'intermediate', 1230, 'En descarga queda el 36.8% al cabo de 1 tau.'))
    q.append(make_mc('Capacitor de placas de 0.02 m2 separadas 1.0 mm en aire (eps_0 = 8.85e-12). ¿C?', '177 pF', ['354 pF', '88.5 pF', '17.7 pF'], 'C = 8.85e-12 * 0.02 / 1e-3 = 177 pF.', 'C = 177 pF.', 'intermediate', 1240, 'Multiplica eps_0 por area sobre distancia.'))
    q.append(make_mc('Dielectrico de constante k = 4 se pone en capacitor aislado con carga cte. ¿Voltaje?', 'Se reduce a la cuarta parte (V/4)', ['Se cuadruplica (4V)', 'Permanece inalterado', 'Cae a cero absoluto'], 'C_nueva = 4C. V_nuevo = q / (4C) = V/4.', 'V se divide por 4.', 'intermediate', 1240, 'La capacidad sube 4 veces, reduciendo el voltaje.'))
    q.append(make_mc('Tiempo convencional para considerar un circuito RC cargado al 99.3%:', '5 tau', ['1 tau', '3 tau', '10 tau'], 'En 5 tau: 1 - e^-5 = 99.3%.', '5 tau.', 'basic', 1170, 'Criterio estandar de 5 constantes de tiempo.'))
    # Teoricas
    q.append(make_mc('La constante de tiempo tau = R·C de un circuito RC representa:', 'El tiempo en que C alcanza el 63.2% de su carga final', ['El tiempo para descargar el 100% de la energia', 'La frecuencia propia de resonancia', 'La vida util del componente'], 'Escala temporal del transitorio exponencial.', 'Tiempo para el 63.2% de carga.', 'basic', 1170, '¿Que fraccion de carga se alcanza en 1 tau?'))
    q.append(make_mc('En el instante inicial t = 0 de la carga de un capacitor descargado, actua como:', 'Un cortocircuito ideal (resistencia nula aparente)', ['Un circuito abierto ideal (resistencia infinita)', 'Una fuente de voltaje infinito', 'Un resistor puro de 1000 ohms'], 'Al no tener voltaje inicial, la corriente es maxima: Vc = 0.', 'Cortocircuito inicial.', 'intermediate', 1230, 'Al no tener carga acumulada, ¿que voltaje opone?'))
    q.append(make_mc('Tras t >> 5 tau en corriente continua, el capacitor cargado se comporta como:', 'Un circuito abierto ideal que bloquea la corriente continua', ['Un cortocircuito que drena toda la corriente', 'Un generador de corriente constante', 'Un superconductor sin resistencia'], 'Alcanzado Vc = V_fuente, la corriente se anula.', 'Circuito abierto para CC.', 'basic', 1180, 'Cuando iguala el voltaje de la fuente, ¿circula corriente?'))
    q.append(make_mc('La funcion de una resistencia de purga (bleeder) en paralelo con C es:', 'Descargar lentamente el capacitor al apagar el equipo por seguridad', ['Aumentar la constante de tiempo de carga', 'Duplicar la capacitancia efectiva', 'Impedir el calentamiento del circuito'], 'Seguridad laboral para evitar descargas accidentales.', 'Descarga de seguridad preventiva.', 'basic', 1180, '¿Por que es peligroso tocar bornes tras desconectar?'))
    q.append(make_mc('La presencia de dielectrico entre placas de un capacitor permite:', 'Aumentar la capacitancia y soportar mayores voltajes', ['Convertir al capacitor en semiconductor', 'Hacer que conduzca corriente continua', 'Eliminar la carga en el metal'], 'C = k * C0 y previene arco electrico.', 'Aumenta C y rigidez dielectrica.', 'basic', 1170, '¿Que efecto produce la polarizacion del dielectrico?'))
    q.append(make_mc('La rigidez dielectrica de un material aislante representa:', 'El campo electrico maximo antes de la ruptura y arco electrico', ['La resistencia mecanica a la traccion', 'El voltaje para cargarlo al 50%', 'La temperatura de fusion del aislante'], 'Limite maximo de E antes de ionizarse.', 'Maximo campo antes de la chispa destructiva.', 'intermediate', 1230, '¿Cual es el limite maximo de campo antes del arco?'))
    q.append(make_mc('La unidad de capacitancia en el Sistema Internacional es el Faradio (F), igual a:', 'Coulomb sobre Volt (C/V)', ['Volt sobre Coulomb (V/C)', 'Joule sobre Ampere (J/A)', 'Ohm por segundo (Omega·s)'], '1 F = 1 C / 1 V.', 'Faradio = Coulomb / Volt.', 'basic', 1140, 'Divide la unidad de carga entre la de potencial.'))
    q.append(make_mc('Durante la descarga de C a traves de R, la energia almacenada:', 'Se disipa como calor por efecto Joule en la resistencia', ['Regresa a la bateria principal', 'Se convierte en radiacion gamma', 'Permanece en el campo magnetico de R'], 'La energia electrostatica se transforma en calor.', 'Se disipa en forma de calor.', 'intermediate', 1220, '¿En que se convierte la energia al descargarse sobre R?'))
    q.append(make_mc('Al conectar dos capacitores iguales en serie, la capacitancia equivalente es:', 'La mitad de la capacitancia individual (C/2)', ['El doble de la individual (2C)', 'Cuatro veces superior', 'Exactamente cero faradios'], 'C_eq = C / 2 en serie.', 'C / 2.', 'basic', 1160, 'En serie se reducen como resistencias en paralelo.'))
    q.append(make_mc('En un capacitor electrolitico es critico respetar la polaridad (+ y -) porque:', 'Conexion inversa destruye el dielectrico de oxido y puede explotar', ['Conectarlo al reves descarga corriente infinita', 'La capacitancia se vuelve negativa', 'Se convierte en fusible de proteccion'], 'El dielectrico solo es estable con voltaje directo.', 'Destruccion del dielectrico y riesgo de explosion.', 'intermediate', 1220, '¿Que riesgo existe al conectar al reves un electrolitico?'))
    return q

def get_questions_practico_tester_extra():
    q = []
    # Ejercicios
    q.append(make_mc('Resistencia 4 bandas: Marron (1), Negro (0), Rojo (10^2), Dorado (5%). ¿Valor?', '1.0 kOhms +- 5%', ['100 Ohms +- 5%', '10 kOhms +- 5%', '1.0 kOhms +- 10%'], '1, 0 y dos ceros = 1000 Ohms = 1.0 kOhms al 5%.', '1.0 kOhms +- 5%.', 'basic', 1170, 'Marron=1, Negro=0, Rojo=dos ceros (x100).'))
    q.append(make_mc('Resistencia 4 bandas: Amarillo (4), Violeta (7), Naranja (10^3), Plateado (10%). ¿Valor?', '47 kOhms +- 10%', ['4.7 kOhms +- 10%', '470 kOhms +- 10%', '47 kOhms +- 5%'], '47 y tres ceros = 47000 Ohms = 47 kOhms al 10%.', '47 kOhms +- 10%.', 'basic', 1180, 'Amarillo=4, Violeta=7, Naranja=x1000.'))
    q.append(make_mc('Resistencia de 100 ohms con 5% de tolerancia. ¿Rango aceptable de medicion?', '95 ohms a 105 ohms', ['90 ohms a 110 ohms', '99 ohms a 101 ohms', '98 ohms a 102 ohms'], '100 +- 5% = 95 a 105 ohms.', '95 a 105 Ohms.', 'basic', 1150, 'Suma y resta el 5% al valor de 100 ohms.'))
    q.append(make_mc('Resistencia de 220 ohms y 0.25 W. ¿Voltaje maximo sin sobrecalentar?', '7.4 V', ['12.0 V', '5.0 V', '10.0 V'], 'V_max = sqrt(P*R) = sqrt(0.25 * 220) = 7.41 V.', 'V = 7.4 V.', 'intermediate', 1240, 'Saca la raiz cuadrada de P por R.'))
    q.append(make_mc('Resistencia de 10 ohms y 2 W sometida a 5.0 V. ¿Condicion de operacion?', 'Disipa 2.5 W superando su limite nominal', ['Disipa 1.0 W trabajando segura', 'Disipa 5.0 W quemandose al instante', 'Disipa 0.5 W perfectamente fria'], 'P = 25 / 10 = 2.5 W > 2 W.', 'Disipa 2.5 W (sobrecalentamiento).', 'intermediate', 1230, 'Calcula V^2 / R y comparala con 2 W.'))
    q.append(make_mc('Tester en escala de 20 V DC marca 1.54 V. En escala de 200 V DC marcara:', '1.5 V (pierde un decimal de resolucion)', ['15.4 V', '1.540 V', '0.15 V'], 'Mayor escala reduce cifras decimales.', '1.5 V.', 'basic', 1160, 'Una escala mayor reduce los decimales mostrados.'))
    q.append(make_mc('Para medir corriente estimada de 150 mA con escalas de 20 mA, 200 mA y 10 A:', 'Se debe usar la escala de 200 mA', ['Se debe usar la escala de 20 mA', 'Se debe usar obligadamente 10 A', 'Cualquiera da igual precision'], 'La escala inmediatamente superior ofrece maxima precision.', 'Escala de 200 mA.', 'basic', 1160, 'Elige la escala mas cercana superior a 150 mA.'))
    q.append(make_mc('Si se intenta medir una resistencia colocada en circuito encendido:', 'La lectura sera erronea y se puede danar el tester', ['La lectura sera exacta mostrando la potencia', 'El tester medira inductancia', 'Se protege la fuente externa'], 'El ohmetro inyecta corriente propia: voltajes externos lo danan.', 'Peligro de dano y lectura falsa.', 'basic', 1160, '¿Debe haber voltaje externo al medir resistencia?'))
    q.append(make_mc('Resistencia 5 bandas: Rojo (2), Rojo (2), Negro (0), Marron (x10), Marron (1%). ¿Valor?', '2.2 kOhms +- 1%', ['220 Ohms +- 1%', '22 kOhms +- 1%', '2.2 kOhms +- 5%'], '2, 2, 0 y un cero = 2200 Ohms = 2.2 kOhms al 1%.', '2.2 kOhms +- 1%.', 'intermediate', 1220, 'Tres digitos significativos mas multiplicador.'))
    q.append(make_mc('Al medir continuidad en cable sano no cortado:', 'El tester emite pitido indicando resistencia casi nula', ['La pantalla muestra sobrecarga OL de circuito abierto', 'Indica 220 V de alterna', 'El fusible interno se funde'], 'Continuidad pita con R menor a 30-50 ohms.', 'Pitido continuo (resistencia nula).', 'basic', 1140, '¿Que aviso sonoro da el tester si el cable conduce?'))
    # Teoricas
    q.append(make_mc('Un multimetro como amperimetro se conecta:', 'Estrictamente en serie abriendo el circuito', ['Estrictamente en paralelo entre bornes', 'Con una punta a masa y otra al chasis', 'En paralelo directo con la fuente'], 'Debe ser atravesado por la corriente de la rama.', 'En serie abriendo la rama.', 'basic', 1160, 'Para medir corriente hay que intercalar el instrumento en la linea.'))
    q.append(make_mc('Conectar el amperimetro por error en paralelo con una bateria produce:', 'Cortocircuito severo que puede fundir el fusible o instrumento', ['Lectura de tension con maxima precision', 'Recarga rapida de la bateria', 'Apagado de pantalla por polarizacion'], 'Resistencia interna casi nula provoca cortocircuito violento.', 'Cortocircuito que quema el fusible interno.', 'basic', 1160, 'El amperimetro tiene resistencia casi nula.'))
    q.append(make_mc('Un voltimetro ideal se caracteriza por tener resistencia interna:', 'Infinitamente grande para no alterar la corriente del circuito', ['Estrictamente nula para permitir el paso', 'Igual a 100 ohms fija', 'Variable segun el estado de su pila'], 'R infinita para no drenar corriente del componente medido.', 'Resistencia interna infinita.', 'basic', 1160, 'Para no desviar corriente de la rama, R debe ser maxima.'))
    q.append(make_mc('Un amperimetro ideal se caracteriza por tener resistencia interna:', 'Estrictamente nula para no introducir caidas de tension extras', ['Infinitamente grande para limitar la corriente', 'Igual a la carga exterior', 'Dependiente del voltaje medido'], 'R nula para no frenar la corriente de la rama.', 'Resistencia interna nula.', 'basic', 1160, 'Para no restar voltaje, su resistencia debe ser cero.'))
    q.append(make_mc('El borne negro COM (Comun) del tester se utiliza como:', 'Punto de referencia comun negativo para todas las mediciones', ['Entrada exclusiva para corrientes altas', 'Conexion a la fase viva domiciliaria', 'Borne de salida para alimentar cargas'], 'COM es la referencia negativa comun.', 'Borne comun de referencia negativa.', 'basic', 1140, '¿Cual es el punto de referencia comun en el multimetro?'))
    q.append(make_mc('Al medir resistencias con el ohmetro, es regla de laboratorio obligatoria:', 'Desconectar alimentacion y descargar capacitores previamente', ['Mantener el circuito a maxima potencia', 'Conectar amperimetro en serie con la punta roja', 'Poner los dedos firmemente en las dos puntas'], 'Evita falsas lecturas y quemar el ohmetro.', 'Desconectar energia y descargar capacitores.', 'basic', 1150, 'No puede haber voltaje residual al medir resistencia.'))
    q.append(make_mc('La tolerancia en el codigo de colores de resistores expresa:', 'El porcentaje maximo de desviacion admisible respecto al valor nominal', ['La potencia maxima disipable en Watts', 'El coeficiente termico en grados', 'El voltaje de aislacion maximo'], 'Dorado = 5%, plateado = 10% de margen.', 'Margen porcentual de variacion.', 'basic', 1150, '¿Que expresa la cuarta banda de color?'))
    q.append(make_mc('En una resistencia sometida a sobrepotencia extrema destructiva:', 'El componente se carboniza y suele abrirse (R tiende a infinito)', ['La resistencia se hace cero superconductor', 'El valor se estabiliza permanente', 'Comienza a emitir campo magnetico'], 'La pelicula resistiva se corta quedando circuito abierto.', 'Falla abriendose a circuito abierto.', 'intermediate', 1230, '¿Que le ocurre al filamento al quemarse por calor extremo?'))
    q.append(make_mc('La seleccion de escalas en multimetro manual debe realizarse:', 'Comenzando por la mas alta si se desconoce la magnitud', ['Comenzando por la mas baja de milivolts', 'Con el circuito encendido y puntas fijas', 'En cualquier orden sin importar'], 'Previene sobrecargas destructivas en el medidor.', 'Comenzar por la escala mas alta.', 'basic', 1150, 'Si no sabes el voltaje, ¿que escala elegis primero?'))
    q.append(make_mc('La curva de derating termico de un resistor indica que a mayor temperatura ambiente:', 'La maxima potencia disipable admisible disminuye', ['La resistencia crece sin limite alguno', 'Puede disipar el doble de potencia', 'La tolerancia cae a cero por ciento'], 'Menor margen termico para disipar sin pasar T_max.', 'Potencia admisible disminuye con la temperatura.', 'intermediate', 1240, 'En ambiente caluroso, ¿puede disipar los mismos Watts sin fundirse?'))
    return q
